In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
lf_regular_season_detailed: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
lf_regular_season_detailed.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [3]:
lf_regular_season_detailed = lf_regular_season_detailed.with_columns(cs.numeric().exclude("Wloc").cast(pl.Int16))
lf_regular_season_detailed.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
lf_regular_season_detailed = ecm.create_team_season_profile(lf_regular_season_detailed)
lf_regular_season_detailed.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────┬───┬─────────────┬──────────┬─────────────┬─────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ TeamFGM   ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRat │
│ ---    ┆ ---    ┆ ---       ┆ ---       ┆   ┆ cy          ┆ ---      ┆ ---         ┆ e           │
│ i16    ┆ i16    ┆ f64       ┆ f64       ┆   ┆ ---         ┆ f64      ┆ f64         ┆ ---         │
│        ┆        ┆           ┆           ┆   ┆ f64         ┆          ┆             ┆ f64         │
╞════════╪════════╪═══════════╪═══════════╪═══╪═════════════╪══════════╪═════════════╪═════════════╡
│ 2009   ┆ 1431   ┆ 75.516129 ┆ 24.806452 ┆ … ┆ 98.824558   ┆ 0.464352 ┆ 0.477657    ┆ 0.174685    │
│ 2024   ┆ 1153   ┆ 74.617647 ┆ 27.617647 ┆ … ┆ 97.602516   ┆ 0.499381 ┆ 0.478014    ┆ 0.162464    │
│ 2017   ┆ 1426   ┆ 76.290323 ┆ 26.806452 ┆ … ┆ 98.795668   ┆ 0.524509 ┆ 0.491116    ┆ 0.189843    │
│ 2026   ┆ 1407   ┆ 80.772727 ┆ 27.727273 ┆ … ┆ 104.901022  ┆ 0.520957 ┆ 0.510944    ┆ 0.155083    │
│ 2012   ┆ 1330   ┆ 65.515152 ┆ 23.454545 ┆ … ┆ 91.970351   ┆ 0.454754 ┆ 0.459736    ┆ 0.206418    │
│ 2011   ┆ 1312   ┆ 67.346154 ┆ 24.115385 ┆ … ┆ 102.14769   ┆ 0.480342 ┆ 0.501693    ┆ 0.190219    │
│ 2026   ┆ 1184   ┆ 76.238095 ┆ 26.238095 ┆ … ┆ 115.768789  ┆ 0.519136 ┆ 0.550801    ┆ 0.163307    │
│ 2007   ┆ 1318   ┆ 62.1875   ┆ 21.71875  ┆ … ┆ 103.388562  ┆ 0.483048 ┆ 0.496221    ┆ 0.193407    │
│ 2022   ┆ 1442   ┆ 77.62069  ┆ 27.655172 ┆ … ┆ 104.160417  ┆ 0.504305 ┆ 0.529711    ┆ 0.15283     │
│ 2009   ┆ 1434   ┆ 59.827586 ┆ 20.931034 ┆ … ┆ 104.387313  ┆ 0.477338 ┆ 0.511688    ┆ 0.234305    │
└────────┴────────┴───────────┴───────────┴───┴─────────────┴──────────┴─────────────┴─────────────┘