In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [3]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2025   ┆ 1271   ┆ 63.296296 ┆ 79.481481   ┆ … ┆ 116.154698  ┆ 0.462714 ┆ 0.553302   ┆ 0.182046   │
│ 2019   ┆ 1298   ┆ 66.483871 ┆ 72.580645   ┆ … ┆ 106.39735   ┆ 0.472016 ┆ 0.522119   ┆ 0.206243   │
│ 2024   ┆ 1105   ┆ 68.69697  ┆ 75.787879   ┆ … ┆ 103.598162  ┆ 0.457754 ┆ 0.491132   ┆ 0.208334   │
│ 2018   ┆ 1167   ┆ 64.222222 ┆ 70.074074   ┆ … ┆ 103.763352  ┆ 0.46647  ┆ 0.507477   ┆ 0.206842   │
│ 2018   ┆ 1358   ┆ 69.827586 ┆ 70.034483   ┆ … ┆ 102.47555   ┆ 0.486354 ┆ 0.51245    ┆ 0.189674   │
│ 2021   ┆ 1410   ┆ 65.6      ┆ 70.0        ┆ … ┆ 96.812534   ┆ 0.4299   ┆ 0.484426   ┆ 0.181437   │
│ 2024   ┆ 1139   ┆ 76.645161 ┆ 73.83871    ┆ … ┆ 103.254669  ┆ 0.517552 ┆ 0.501033   ┆ 0.14432    │
│ 2016   ┆ 1178   ┆ 82.241379 ┆ 83.862069   ┆ … ┆ 111.075377  ┆ 0.522971 ┆ 0.538312   ┆ 0.178888   │
│ 2017   ┆ 1187   ┆ 63.272727 ┆ 65.090909   ┆ … ┆ 98.373531   ┆ 0.456958 ┆ 0.450305   ┆ 0.207527   │
│ 2024   ┆ 1359   ┆ 84.34375  ┆ 74.375      ┆ … ┆ 100.364122  ┆ 0.56827  ┆ 0.501523   ┆ 0.170182   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [5]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [6]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [7]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2025   ┆ 1384   ┆ 68.0      ┆ 70.0        ┆ … ┆ 106.221548  ┆ 0.604167 ┆ 0.492857   ┆ 0.225056   │
│ 2025   ┆ 1110   ┆ 72.0      ┆ 83.0        ┆ … ┆ 127.54514   ┆ 0.587719 ┆ 0.663462   ┆ 0.197568   │
│ 2024   ┆ 1211   ┆ 81.0      ┆ 71.0        ┆ … ┆ 107.121274  ┆ 0.604929 ┆ 0.49045    ┆ 0.13881    │
│ 2016   ┆ 1246   ┆ 76.0      ┆ 65.0        ┆ … ┆ 90.947935   ┆ 0.505848 ┆ 0.410678   ┆ 0.181421   │
│ 2016   ┆ 1139   ┆ 70.0      ┆ 69.0        ┆ … ┆ 105.273929  ┆ 0.553105 ┆ 0.55235    ┆ 0.140578   │
│ 2019   ┆ 1285   ┆ 55.0      ┆ 74.0        ┆ … ┆ 108.187135  ┆ 0.383333 ┆ 0.539216   ┆ 0.146681   │
│ 2023   ┆ 1417   ┆ 76.666667 ┆ 65.0        ┆ … ┆ 97.295304   ┆ 0.539232 ┆ 0.467325   ┆ 0.102345   │
│ 2024   ┆ 1438   ┆ 42.0      ┆ 67.0        ┆ … ┆ 114.236999  ┆ 0.276786 ┆ 0.606383   ┆ 0.048329   │
│ 2024   ┆ 1228   ┆ 74.5      ┆ 69.5        ┆ … ┆ 102.416566  ┆ 0.523779 ┆ 0.481344   ┆ 0.12779    │
│ 2023   ┆ 1436   ┆ 61.0      ┆ 78.0        ┆ … ┆ 123.564356  ┆ 0.509434 ┆ 0.607143   ┆ 0.156863   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [8]:
m_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneySeeds.csv")
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [9]:
m_tourney_seed_lf = m_tourney_seed_lf.with_columns(cs.numeric().exclude("Seed").cast(pl.Int16))
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [10]:
m_tourney_seed_lf = ecm.seed_cleaning(m_tourney_seed_lf)
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 1437   │
│ 2015   ┆ 2    ┆ 1438   │
│ 2015   ┆ 3    ┆ 1328   │
│ 2015   ┆ 4    ┆ 1257   │
│ 2015   ┆ 5    ┆ 1320   │
│ 2015   ┆ 6    ┆ 1344   │
│ 2015   ┆ 7    ┆ 1277   │
│ 2015   ┆ 8    ┆ 1301   │
│ 2015   ┆ 9    ┆ 1261   │
│ 2015   ┆ 10   ┆ 1208   │
└────────┴──────┴────────┘

**Women's NCCA data**

In [11]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [12]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [13]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2018   ┆ 3421   ┆ 59.741935 ┆ 59.741935   ┆ … ┆ 92.099446   ┆ 0.443973 ┆ 0.455616   ┆ 0.220571   │
│ 2024   ┆ 3391   ┆ 56.758621 ┆ 59.482759   ┆ … ┆ 87.372997   ┆ 0.416965 ┆ 0.441273   ┆ 0.218724   │
│ 2017   ┆ 3330   ┆ 71.032258 ┆ 69.419355   ┆ … ┆ 97.091497   ┆ 0.489098 ┆ 0.458229   ┆ 0.248641   │
│ 2021   ┆ 3372   ┆ 80.5      ┆ 51.791667   ┆ … ┆ 70.656704   ┆ 0.554603 ┆ 0.37718    ┆ 0.212689   │
│ 2025   ┆ 3429   ┆ 65.483871 ┆ 78.032258   ┆ … ┆ 102.284358  ┆ 0.436669 ┆ 0.516883   ┆ 0.204055   │
│ 2018   ┆ 3183   ┆ 58.689655 ┆ 72.137931   ┆ … ┆ 101.839552  ┆ 0.428974 ┆ 0.481641   ┆ 0.231464   │
│ 2015   ┆ 3142   ┆ 67.275862 ┆ 66.965517   ┆ … ┆ 90.61779    ┆ 0.439591 ┆ 0.441183   ┆ 0.226405   │
│ 2025   ┆ 3292   ┆ 64.382353 ┆ 51.852941   ┆ … ┆ 76.766825   ┆ 0.472349 ┆ 0.377995   ┆ 0.184105   │
│ 2019   ┆ 3229   ┆ 62.5      ┆ 61.833333   ┆ … ┆ 91.014576   ┆ 0.462799 ┆ 0.446025   ┆ 0.236158   │
│ 2021   ┆ 3360   ┆ 63.722222 ┆ 59.722222   ┆ … ┆ 83.049954   ┆ 0.437829 ┆ 0.461665   ┆ 0.20875    │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [14]:
w_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [15]:
w_tourney_detailed_lf = w_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [16]:
w_tourney_detailed_lf = ecm.create_team_season_profile(w_tourney_detailed_lf)
w_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2023   ┆ 3328   ┆ 79.0      ┆ 72.5        ┆ … ┆ 91.430206   ┆ 0.472783 ┆ 0.446509   ┆ 0.209954   │
│ 2015   ┆ 3163   ┆ 86.666667 ┆ 53.833333   ┆ … ┆ 78.608028   ┆ 0.601381 ┆ 0.388343   ┆ 0.162096   │
│ 2021   ┆ 3163   ┆ 81.0      ┆ 62.8        ┆ … ┆ 85.721211   ┆ 0.546588 ┆ 0.424216   ┆ 0.16226    │
│ 2019   ┆ 3138   ┆ 77.0      ┆ 77.5        ┆ … ┆ 104.495848  ┆ 0.486477 ┆ 0.481909   ┆ 0.249313   │
│ 2024   ┆ 3401   ┆ 59.0      ┆ 61.0        ┆ … ┆ 91.798345   ┆ 0.418033 ┆ 0.428571   ┆ 0.230964   │
│ 2019   ┆ 3340   ┆ 40.0      ┆ 78.0        ┆ … ┆ 125.55332   ┆ 0.326531 ┆ 0.52381    ┆ 0.268881   │
│ 2023   ┆ 3405   ┆ 63.5      ┆ 83.5        ┆ … ┆ 105.376977  ┆ 0.431452 ┆ 0.4621     ┆ 0.142261   │
│ 2015   ┆ 3401   ┆ 60.0      ┆ 69.0        ┆ … ┆ 112.195122  ┆ 0.396552 ┆ 0.509091   ┆ 0.187281   │
│ 2024   ┆ 3304   ┆ 56.0      ┆ 60.0        ┆ … ┆ 85.092616   ┆ 0.385928 ┆ 0.459016   ┆ 0.160395   │
│ 2021   ┆ 3268   ┆ 86.333333 ┆ 57.666667   ┆ … ┆ 84.771159   ┆ 0.557441 ┆ 0.425664   ┆ 0.155829   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [17]:
w_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneySeeds.csv")
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [18]:
w_tourney_seed_lf = w_tourney_seed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [19]:
w_tourney_seed_lf = ecm.seed_cleaning(w_tourney_seed_lf)
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 3163   │
│ 2015   ┆ 2    ┆ 3246   │
│ 2015   ┆ 3    ┆ 3257   │
│ 2015   ┆ 4    ┆ 3143   │
│ 2015   ┆ 5    ┆ 3400   │
│ 2015   ┆ 6    ┆ 3378   │
│ 2015   ┆ 7    ┆ 3173   │
│ 2015   ┆ 8    ┆ 3353   │
│ 2015   ┆ 9    ┆ 3371   │
│ 2015   ┆ 10   ┆ 3235   │
└────────┴──────┴────────┘