In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [3]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2017   ┆ 1124   ┆ 71.612903 ┆ 63.032258   ┆ … ┆ 97.86618    ┆ 0.526064 ┆ 0.457178   ┆ 0.205745   │
│ 2026   ┆ 1393   ┆ 75.826087 ┆ 70.695652   ┆ … ┆ 101.011821  ┆ 0.532186 ┆ 0.480218   ┆ 0.15046    │
│ 2022   ┆ 1190   ┆ 70.8      ┆ 73.2        ┆ … ┆ 109.117508  ┆ 0.52056  ┆ 0.534412   ┆ 0.161599   │
│ 2015   ┆ 1111   ┆ 63.482759 ┆ 70.103448   ┆ … ┆ 104.978376  ┆ 0.457698 ┆ 0.506106   ┆ 0.206113   │
│ 2023   ┆ 1104   ┆ 82.176471 ┆ 68.5        ┆ … ┆ 89.411087   ┆ 0.52876  ┆ 0.416056   ┆ 0.17941    │
│ 2018   ┆ 1310   ┆ 83.84375  ┆ 83.9375     ┆ … ┆ 111.027792  ┆ 0.515993 ┆ 0.526516   ┆ 0.149553   │
│ 2024   ┆ 1143   ┆ 73.96875  ┆ 77.03125    ┆ … ┆ 105.809974  ┆ 0.493488 ┆ 0.511831   ┆ 0.149401   │
│ 2025   ┆ 1246   ┆ 85.30303  ┆ 77.878788   ┆ … ┆ 105.425062  ┆ 0.560321 ┆ 0.506529   ┆ 0.141803   │
│ 2018   ┆ 1333   ┆ 73.09375  ┆ 70.34375    ┆ … ┆ 103.245897  ┆ 0.520836 ┆ 0.49954    ┆ 0.191951   │
│ 2026   ┆ 1469   ┆ 73.52381  ┆ 76.190476   ┆ … ┆ 107.523908  ┆ 0.526985 ┆ 0.50915    ┆ 0.169085   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [5]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [6]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [7]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2018   ┆ 1274   ┆ 62.0      ┆ 64.0        ┆ … ┆ 104.447164  ┆ 0.55102  ┆ 0.545455   ┆ 0.257338   │
│ 2022   ┆ 1353   ┆ 87.0      ┆ 89.0        ┆ … ┆ 114.690722  ┆ 0.584507 ┆ 0.555556   ┆ 0.176032   │
│ 2016   ┆ 1428   ┆ 69.5      ┆ 75.5        ┆ … ┆ 114.18294   ┆ 0.550192 ┆ 0.593876   ┆ 0.253097   │
│ 2023   ┆ 1268   ┆ 59.0      ┆ 69.0        ┆ … ┆ 103.7503    ┆ 0.469444 ┆ 0.456281   ┆ 0.197113   │
│ 2018   ┆ 1397   ┆ 67.5      ┆ 55.0        ┆ … ┆ 91.112028   ┆ 0.514015 ┆ 0.470455   ┆ 0.149563   │
│ 2021   ┆ 1328   ┆ 71.5      ┆ 77.5        ┆ … ┆ 112.88474   ┆ 0.512461 ┆ 0.517771   ┆ 0.131264   │
│ 2023   ┆ 1388   ┆ 59.0      ┆ 60.5        ┆ … ┆ 95.36477    ┆ 0.433673 ┆ 0.529184   ┆ 0.129229   │
│ 2016   ┆ 1112   ┆ 55.0      ┆ 65.0        ┆ … ┆ 99.961553   ┆ 0.479167 ┆ 0.432203   ┆ 0.296296   │
│ 2015   ┆ 1157   ┆ 72.0      ┆ 86.0        ┆ … ┆ 135.007849  ┆ 0.543103 ┆ 0.631148   ┆ 0.096424   │
│ 2025   ┆ 1252   ┆ 55.0      ┆ 82.0        ┆ … ┆ 119.186047  ┆ 0.45098  ┆ 0.641667   ┆ 0.247453   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [8]:
m_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneySeeds.csv")
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [9]:
m_tourney_seed_lf = m_tourney_seed_lf.with_columns(cs.numeric().exclude("Seed").cast(pl.Int16))
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [10]:
m_tourney_seed_lf = ecm.clean_seed(m_tourney_seed_lf)
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 1437   │
│ 2015   ┆ 2    ┆ 1438   │
│ 2015   ┆ 3    ┆ 1328   │
│ 2015   ┆ 4    ┆ 1257   │
│ 2015   ┆ 5    ┆ 1320   │
│ 2015   ┆ 6    ┆ 1344   │
│ 2015   ┆ 7    ┆ 1277   │
│ 2015   ┆ 8    ┆ 1301   │
│ 2015   ┆ 9    ┆ 1261   │
│ 2015   ┆ 10   ┆ 1208   │
└────────┴──────┴────────┘

In [11]:
m_golden_tabel_lf: pl.LazyFrame = ecm.merge_seed_with_regular(m_tourney_seed_lf, m_regular_season_detailed_lf)
m_golden_tabel_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2022   ┆ 1443   ┆ 73.966667 ┆ 70.9          ┆ … ┆ 0.530373 ┆ 0.507489    ┆ 0.165387     ┆ null │
│ 2022   ┆ 1209   ┆ 68.32     ┆ 67.24         ┆ … ┆ 0.451552 ┆ 0.498697    ┆ 0.159454     ┆ 16   │
│ 2015   ┆ 1129   ┆ 69.870968 ┆ 60.935484     ┆ … ┆ 0.53805  ┆ 0.476858    ┆ 0.161214     ┆ 11   │
│ 2023   ┆ 1340   ┆ 73.655172 ┆ 78.241379     ┆ … ┆ 0.496493 ┆ 0.550594    ┆ 0.159647     ┆ null │
│ 2023   ┆ 1157   ┆ 70.142857 ┆ 77.321429     ┆ … ┆ 0.475191 ┆ 0.533994    ┆ 0.167375     ┆ null │
│ 2019   ┆ 1357   ┆ 78.83871  ┆ 78.612903     ┆ … ┆ 0.521829 ┆ 0.522184    ┆ 0.198275     ┆ null │
│ 2019   ┆ 1370   ┆ 71.666667 ┆ 69.033333     ┆ … ┆ 0.490536 ┆ 0.465626    ┆ 0.174987     ┆ null │
│ 2018   ┆ 1122   ┆ 71.733333 ┆ 72.966667     ┆ … ┆ 0.500547 ┆ 0.543229    ┆ 0.202519     ┆ null │
│ 2017   ┆ 1159   ┆ 66.258065 ┆ 71.129032     ┆ … ┆ 0.51815  ┆ 0.526568    ┆ 0.220048     ┆ null │
│ 2026   ┆ 1261   ┆ 82.818182 ┆ 74.363636     ┆ … ┆ 0.553267 ┆ 0.495808    ┆ 0.148908     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [12]:
del m_regular_season_detailed_lf, m_tourney_seed_lf

In [13]:
m_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_matchups_lf = ecm.prepare_tourney_matchups(m_tourney_matchups_lf)
m_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ 1      │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ 1      │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ 1      │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ 1      │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ 1      │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ 1      │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ 1      │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ 1      │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ 1      │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

In [14]:
m_train_data_lf: pl.LazyFrame = ecm.finalize_training_data(m_tourney_matchups_lf, m_golden_tabel_lf)
m_train_data_lf.head(10).collect()

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ … ┆ -0.040666    ┆ -0.014806    ┆ -0.007078    ┆ 0         │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ … ┆ -0.047807    ┆ -0.024097    ┆ 0.002589     ┆ 0         │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ … ┆ -0.008537    ┆ -0.001035    ┆ 0.017282     ┆ 0         │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ … ┆ -0.02873     ┆ 0.003899     ┆ 0.022644     ┆ 0         │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ … ┆ 0.037546     ┆ -0.04521     ┆ -0.031617    ┆ -13       │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ … ┆ -0.016964    ┆ 0.01076      ┆ -0.006101    ┆ -7        │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ … ┆ -0.000487    ┆ 0.047622     ┆ -0.024455    ┆ -5        │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ … ┆ -0.000502    ┆ -0.007881    ┆ 0.014252     ┆ -1        │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ … ┆ -0.044199    ┆ -0.053542    ┆ 0.032444     ┆ -9        │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ … ┆ 0.021938     ┆ -0.013491    ┆ -0.030793    ┆ 11        │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [15]:
del m_tourney_matchups_lf, m_golden_tabel_lf

In [18]:
m_train_data_df: pl.DataFrame = m_train_data_lf.collect()
m_train_data_df.write_parquet("../data/proccessed/m_train_data.parquet")

**Women's NCCA data**

In [ ]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [ ]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [ ]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2026   ┆ 3393   ┆ 74.863636 ┆ 61.045455   ┆ … ┆ 79.765264   ┆ 0.461342 ┆ 0.426893   ┆ 0.20245    │
│ 2022   ┆ 3246   ┆ 72.5      ┆ 65.533333   ┆ … ┆ 89.457295   ┆ 0.479043 ┆ 0.452018   ┆ 0.181183   │
│ 2025   ┆ 3400   ┆ 78.941176 ┆ 55.911765   ┆ … ┆ 77.582177   ┆ 0.485286 ┆ 0.41773    ┆ 0.174843   │
│ 2024   ┆ 3144   ┆ 57.827586 ┆ 56.62069    ┆ … ┆ 84.844896   ┆ 0.47552  ┆ 0.424388   ┆ 0.243394   │
│ 2018   ┆ 3333   ┆ 73.566667 ┆ 58.066667   ┆ … ┆ 87.237093   ┆ 0.559548 ┆ 0.384491   ┆ 0.212839   │
│ 2026   ┆ 3116   ┆ 73.130435 ┆ 74.73913    ┆ … ┆ 94.09968    ┆ 0.456424 ┆ 0.470782   ┆ 0.209034   │
│ 2021   ┆ 3175   ┆ 58.214286 ┆ 64.214286   ┆ … ┆ 87.112937   ┆ 0.392194 ┆ 0.443516   ┆ 0.2273     │
│ 2023   ┆ 3157   ┆ 68.321429 ┆ 70.714286   ┆ … ┆ 95.0217     ┆ 0.46647  ┆ 0.459622   ┆ 0.223136   │
│ 2025   ┆ 3349   ┆ 65.882353 ┆ 62.852941   ┆ … ┆ 86.540087   ┆ 0.459554 ┆ 0.427431   ┆ 0.212496   │
│ 2015   ┆ 3230   ┆ 56.04     ┆ 68.8        ┆ … ┆ 98.804169   ┆ 0.405473 ┆ 0.495484   ┆ 0.261968   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [ ]:
w_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [ ]:
w_tourney_detailed_lf = w_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [ ]:
w_tourney_detailed_lf = ecm.create_team_season_profile(w_tourney_detailed_lf)
w_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2017   ┆ 3173   ┆ 57.0      ┆ 66.0        ┆ … ┆ 98.987627   ┆ 0.353846 ┆ 0.423077   ┆ 0.118256   │
│ 2017   ┆ 3107   ┆ 55.0      ┆ 116.0       ┆ … ┆ 151.633987  ┆ 0.353846 ┆ 0.717391   ┆ 0.250991   │
│ 2021   ┆ 3292   ┆ 62.0      ┆ 87.0        ┆ … ┆ 116.935484  ┆ 0.411765 ┆ 0.539683   ┆ 0.14044    │
│ 2017   ┆ 3281   ┆ 60.5      ┆ 70.5        ┆ … ┆ 104.788163  ┆ 0.464367 ┆ 0.490838   ┆ 0.269384   │
│ 2022   ┆ 3273   ┆ 38.0      ┆ 83.0        ┆ … ┆ 113.659706  ┆ 0.258929 ┆ 0.537313   ┆ 0.247763   │
│ 2018   ┆ 3332   ┆ 86.5      ┆ 67.75       ┆ … ┆ 95.930252   ┆ 0.569777 ┆ 0.425258   ┆ 0.117392   │
│ 2018   ┆ 3173   ┆ 65.0      ┆ 84.0        ┆ … ┆ 115.782219  ┆ 0.412281 ┆ 0.529412   ┆ 0.264164   │
│ 2016   ┆ 3199   ┆ 68.0      ┆ 63.0        ┆ … ┆ 88.36152    ┆ 0.460839 ┆ 0.457038   ┆ 0.260828   │
│ 2022   ┆ 3211   ┆ 63.5      ┆ 61.5        ┆ … ┆ 94.97781    ┆ 0.464464 ┆ 0.427455   ┆ 0.227866   │
│ 2019   ┆ 3277   ┆ 75.5      ┆ 89.0        ┆ … ┆ 120.19075   ┆ 0.492537 ┆ 0.54328    ┆ 0.163162   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [ ]:
w_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneySeeds.csv")
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [ ]:
w_tourney_seed_lf = w_tourney_seed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [ ]:
w_tourney_seed_lf = ecm.clean_seed(w_tourney_seed_lf)
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 3163   │
│ 2015   ┆ 2    ┆ 3246   │
│ 2015   ┆ 3    ┆ 3257   │
│ 2015   ┆ 4    ┆ 3143   │
│ 2015   ┆ 5    ┆ 3400   │
│ 2015   ┆ 6    ┆ 3378   │
│ 2015   ┆ 7    ┆ 3173   │
│ 2015   ┆ 8    ┆ 3353   │
│ 2015   ┆ 9    ┆ 3371   │
│ 2015   ┆ 10   ┆ 3235   │
└────────┴──────┴────────┘

In [ ]:
w_golden_table_lf: pl.LazyFrame = ecm.merge_seed_with_regular(w_tourney_seed_lf, w_regular_season_detailed_lf)
w_golden_table_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2025   ┆ 3278   ┆ 73.483871 ┆ 61.193548     ┆ … ┆ 0.488769 ┆ 0.461865    ┆ 0.1514       ┆ null │
│ 2022   ┆ 3321   ┆ 66.896552 ┆ 63.862069     ┆ … ┆ 0.44029  ┆ 0.45734     ┆ 0.179583     ┆ null │
│ 2023   ┆ 3463   ┆ 59.518519 ┆ 64.62963      ┆ … ┆ 0.420978 ┆ 0.460989    ┆ 0.233809     ┆ null │
│ 2022   ┆ 3111   ┆ 67.875    ┆ 69.75         ┆ … ┆ 0.469762 ┆ 0.449467    ┆ 0.235        ┆ null │
│ 2025   ┆ 3188   ┆ 62.888889 ┆ 75.222222     ┆ … ┆ 0.443401 ┆ 0.487584    ┆ 0.214607     ┆ null │
│ 2024   ┆ 3473   ┆ 63.555556 ┆ 72.777778     ┆ … ┆ 0.446191 ┆ 0.527018    ┆ 0.187322     ┆ null │
│ 2017   ┆ 3323   ┆ 79.454545 ┆ 61.242424     ┆ … ┆ 0.540719 ┆ 0.449096    ┆ 0.182922     ┆ 1    │
│ 2019   ┆ 3409   ┆ 57.83871  ┆ 63.387097     ┆ … ┆ 0.397688 ┆ 0.459092    ┆ 0.214001     ┆ null │
│ 2017   ┆ 3308   ┆ 68.142857 ┆ 60.214286     ┆ … ┆ 0.475653 ┆ 0.42348     ┆ 0.224176     ┆ 15   │
│ 2024   ┆ 3409   ┆ 70.8125   ┆ 67.1875       ┆ … ┆ 0.49218  ┆ 0.422678    ┆ 0.203308     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [ ]:
del w_tourney_seed_lf, w_regular_season_detailed_lf

In [ ]:
w_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_matchups_lf = ecm.prepare_tourney_matchups(w_tourney_matchups_lf)
w_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ 1      │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ 1      │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ 1      │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ 1      │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ 1      │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ 1      │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ 1      │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ 1      │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ 1      │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

In [ ]:
w_train_data_lf: pl.LazyFrame = ecm.finalize_training_data(w_tourney_matchups_lf, w_golden_table_lf)
w_train_data_lf.head(10).collect()

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ … ┆ -0.065267    ┆ -0.022153    ┆ 0.002366     ┆ 3         │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ … ┆ 0.06781      ┆ -0.053646    ┆ -0.008088    ┆ -13       │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ … ┆ 0.002632     ┆ 0.000894     ┆ 0.012675     ┆ -9        │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ … ┆ 0.010844     ┆ -0.037637    ┆ 0.030525     ┆ -3        │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ … ┆ 0.028656     ┆ 0.038958     ┆ -0.047683    ┆ 1         │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ … ┆ -0.018015    ┆ -0.041011    ┆ 0.009153     ┆ -9        │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ … ┆ 0.030676     ┆ 0.016624     ┆ 0.003185     ┆ 5         │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ … ┆ 0.03694      ┆ 0.048403     ┆ -0.012815    ┆ -11       │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ … ┆ 0.001469     ┆ -0.000361    ┆ -0.013834    ┆ -13       │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ … ┆ -0.047435    ┆ -0.002718    ┆ 0.041146     ┆ 5         │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [ ]:
del w_tourney_matchups_lf, w_golden_table_lf