In [21]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [22]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [23]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [24]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2015   ┆ 1442   ┆ 60.846154 ┆ 71.730769   ┆ … ┆ 106.575431  ┆ 0.454337 ┆ 0.507427   ┆ 0.182709   │
│ 2015   ┆ 1405   ┆ 75.242424 ┆ 71.0        ┆ … ┆ 105.292371  ┆ 0.526679 ┆ 0.498904   ┆ 0.179388   │
│ 2018   ┆ 1164   ┆ 60.78125  ┆ 74.5        ┆ … ┆ 105.747444  ┆ 0.432438 ┆ 0.496797   ┆ 0.204247   │
│ 2022   ┆ 1374   ┆ 74.354839 ┆ 67.16129    ┆ … ┆ 94.335568   ┆ 0.521945 ┆ 0.451325   ┆ 0.167126   │
│ 2018   ┆ 1391   ┆ 73.142857 ┆ 79.071429   ┆ … ┆ 108.416341  ┆ 0.490847 ┆ 0.549618   ┆ 0.148042   │
│ 2022   ┆ 1426   ┆ 64.777778 ┆ 69.333333   ┆ … ┆ 99.816149   ┆ 0.455869 ┆ 0.495298   ┆ 0.18699    │
│ 2016   ┆ 1425   ┆ 80.848485 ┆ 74.757576   ┆ … ┆ 101.468003  ┆ 0.51987  ┆ 0.477107   ┆ 0.164919   │
│ 2026   ┆ 1333   ┆ 70.6      ┆ 74.12       ┆ … ┆ 108.600645  ┆ 0.498193 ┆ 0.502015   ┆ 0.166093   │
│ 2019   ┆ 1338   ┆ 69.878788 ┆ 68.69697    ┆ … ┆ 99.585804   ┆ 0.478198 ┆ 0.484073   ┆ 0.197219   │
│ 2015   ┆ 1416   ┆ 65.689655 ┆ 72.206897   ┆ … ┆ 109.753865  ┆ 0.493758 ┆ 0.514423   ┆ 0.198874   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [25]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [26]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [27]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2021   ┆ 1276   ┆ 73.25     ┆ 63.25       ┆ … ┆ 90.096317   ┆ 0.534487 ┆ 0.415076   ┆ 0.170421   │
│ 2015   ┆ 1214   ┆ 65.0      ┆ 71.5        ┆ … ┆ 94.734792   ┆ 0.420451 ┆ 0.451481   ┆ 0.164139   │
│ 2022   ┆ 1350   ┆ 59.0      ┆ 71.0        ┆ … ┆ 108.625826  ┆ 0.435286 ┆ 0.51936    ┆ 0.125916   │
│ 2019   ┆ 1205   ┆ 56.0      ┆ 71.0        ┆ … ┆ 112.386229  ┆ 0.53     ┆ 0.583333   ┆ 0.254372   │
│ 2021   ┆ 1159   ┆ 68.0      ┆ 85.0        ┆ … ┆ 107.902253  ┆ 0.5      ┆ 0.484615   ┆ 0.274742   │
│ 2025   ┆ 1345   ┆ 70.333333 ┆ 62.333333   ┆ … ┆ 102.214316  ┆ 0.513198 ┆ 0.496017   ┆ 0.171575   │
│ 2019   ┆ 1261   ┆ 70.333333 ┆ 73.666667   ┆ … ┆ 106.603655  ┆ 0.452501 ┆ 0.467833   ┆ 0.143821   │
│ 2025   ┆ 1251   ┆ 52.0      ┆ 81.0        ┆ … ┆ 120.490889  ┆ 0.393443 ┆ 0.631579   ┆ 0.176991   │
│ 2015   ┆ 1235   ┆ 59.0      ┆ 60.0        ┆ … ┆ 87.944302   ┆ 0.415385 ┆ 0.369565   ┆ 0.156417   │
│ 2022   ┆ 1397   ┆ 78.0      ┆ 66.0        ┆ … ┆ 95.426959   ┆ 0.580054 ┆ 0.503739   ┆ 0.132921   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [28]:
m_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneySeeds.csv")
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [29]:
m_tourney_seed_lf = m_tourney_seed_lf.with_columns(cs.numeric().exclude("Seed").cast(pl.Int16))
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [30]:
m_tourney_seed_lf = ecm.clean_seed(m_tourney_seed_lf)
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 1437   │
│ 2015   ┆ 2    ┆ 1438   │
│ 2015   ┆ 3    ┆ 1328   │
│ 2015   ┆ 4    ┆ 1257   │
│ 2015   ┆ 5    ┆ 1320   │
│ 2015   ┆ 6    ┆ 1344   │
│ 2015   ┆ 7    ┆ 1277   │
│ 2015   ┆ 8    ┆ 1301   │
│ 2015   ┆ 9    ┆ 1261   │
│ 2015   ┆ 10   ┆ 1208   │
└────────┴──────┴────────┘

In [31]:
m_golden_tabel_lf: pl.LazyFrame = ecm.merge_seed_with_regular(m_tourney_seed_lf, m_regular_season_detailed_lf)
m_golden_tabel_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2019   ┆ 1413   ┆ 64.310345 ┆ 69.068966     ┆ … ┆ 0.490421 ┆ 0.529926    ┆ 0.198438     ┆ null │
│ 2018   ┆ 1350   ┆ 71.78125  ┆ 75.5625       ┆ … ┆ 0.523121 ┆ 0.557771    ┆ 0.168009     ┆ null │
│ 2021   ┆ 1437   ┆ 75.545455 ┆ 67.136364     ┆ … ┆ 0.529116 ┆ 0.519563    ┆ 0.124362     ┆ 5    │
│ 2024   ┆ 1421   ┆ 75.935484 ┆ 74.870968     ┆ … ┆ 0.523415 ┆ 0.504987    ┆ 0.161464     ┆ null │
│ 2025   ┆ 1466   ┆ 78.03125  ┆ 71.03125      ┆ … ┆ 0.51771  ┆ 0.505987    ┆ 0.112829     ┆ null │
│ 2016   ┆ 1274   ┆ 75.625    ┆ 66.8125       ┆ … ┆ 0.540526 ┆ 0.480998    ┆ 0.160432     ┆ 3    │
│ 2016   ┆ 1256   ┆ 78.8      ┆ 74.166667     ┆ … ┆ 0.514939 ┆ 0.49215     ┆ 0.169062     ┆ null │
│ 2018   ┆ 1268   ┆ 72.967742 ┆ 67.129032     ┆ … ┆ 0.54577  ┆ 0.478464    ┆ 0.202511     ┆ null │
│ 2023   ┆ 1407   ┆ 70.433333 ┆ 67.8          ┆ … ┆ 0.495325 ┆ 0.4866      ┆ 0.174829     ┆ null │
│ 2019   ┆ 1195   ┆ 70.4      ┆ 74.033333     ┆ … ┆ 0.526187 ┆ 0.522891    ┆ 0.213558     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

**Women's NCCA data**

In [32]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [33]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [34]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2024   ┆ 3444   ┆ 62.241379 ┆ 66.310345   ┆ … ┆ 94.323882   ┆ 0.480745 ┆ 0.487188   ┆ 0.209342   │
│ 2019   ┆ 3277   ┆ 75.096774 ┆ 67.322581   ┆ … ┆ 92.358604   ┆ 0.495299 ┆ 0.466331   ┆ 0.195525   │
│ 2017   ┆ 3427   ┆ 69.928571 ┆ 69.535714   ┆ … ┆ 94.300325   ┆ 0.452329 ┆ 0.468835   ┆ 0.200004   │
│ 2024   ┆ 3393   ┆ 74.366667 ┆ 65.366667   ┆ … ┆ 88.662715   ┆ 0.47031  ┆ 0.443965   ┆ 0.187727   │
│ 2015   ┆ 3162   ┆ 61.428571 ┆ 67.928571   ┆ … ┆ 93.837068   ┆ 0.400245 ┆ 0.44294    ┆ 0.253603   │
│ 2026   ┆ 3210   ┆ 66.130435 ┆ 67.565217   ┆ … ┆ 88.839      ┆ 0.435419 ┆ 0.436167   ┆ 0.216342   │
│ 2026   ┆ 3406   ┆ 63.4      ┆ 67.5        ┆ … ┆ 91.880172   ┆ 0.429711 ┆ 0.441165   ┆ 0.199681   │
│ 2023   ┆ 3309   ┆ 61.464286 ┆ 67.214286   ┆ … ┆ 91.034873   ┆ 0.414323 ┆ 0.464129   ┆ 0.250943   │
│ 2024   ┆ 3461   ┆ 62.344828 ┆ 60.689655   ┆ … ┆ 91.564161   ┆ 0.507442 ┆ 0.464675   ┆ 0.201215   │
│ 2022   ┆ 3158   ┆ 72.655172 ┆ 68.034483   ┆ … ┆ 89.338998   ┆ 0.44702  ┆ 0.448674   ┆ 0.168908   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [35]:
w_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [36]:
w_tourney_detailed_lf = w_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [37]:
w_tourney_detailed_lf = ecm.create_team_season_profile(w_tourney_detailed_lf)
w_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2017   ┆ 3411   ┆ 30.0      ┆ 119.0       ┆ … ┆ 148.610677  ┆ 0.172414 ┆ 0.690789   ┆ 0.2688     │
│ 2017   ┆ 3442   ┆ 66.0      ┆ 87.0        ┆ … ┆ 109.502832  ┆ 0.467213 ┆ 0.521739   ┆ 0.2048     │
│ 2017   ┆ 3199   ┆ 73.5      ┆ 61.25       ┆ … ┆ 83.04865    ┆ 0.459989 ┆ 0.469946   ┆ 0.187637   │
│ 2024   ┆ 3414   ┆ 56.0      ┆ 75.0        ┆ … ┆ 111.399926  ┆ 0.355932 ┆ 0.547619   ┆ 0.21021    │
│ 2025   ┆ 3471   ┆ 56.0      ┆ 68.0        ┆ … ┆ 99.125364   ┆ 0.418033 ┆ 0.54902    ┆ 0.211715   │
│ 2019   ┆ 3416   ┆ 45.0      ┆ 60.0        ┆ … ┆ 95.69378    ┆ 0.339286 ┆ 0.490196   ┆ 0.178138   │
│ 2015   ┆ 3177   ┆ 73.0      ┆ 75.5        ┆ … ┆ 99.021328   ┆ 0.443452 ┆ 0.527945   ┆ 0.149976   │
│ 2016   ┆ 3326   ┆ 79.333333 ┆ 76.0        ┆ … ┆ 96.27585    ┆ 0.472739 ┆ 0.473464   ┆ 0.131444   │
│ 2017   ┆ 3211   ┆ 62.0      ┆ 75.0        ┆ … ┆ 102.774923  ┆ 0.359155 ┆ 0.528302   ┆ 0.180243   │
│ 2016   ┆ 3378   ┆ 57.5      ┆ 58.5        ┆ … ┆ 87.548643   ┆ 0.35653  ┆ 0.421315   ┆ 0.154468   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [38]:
w_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneySeeds.csv")
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [39]:
w_tourney_seed_lf = w_tourney_seed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [40]:
w_tourney_seed_lf = ecm.clean_seed(w_tourney_seed_lf)
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 3163   │
│ 2015   ┆ 2    ┆ 3246   │
│ 2015   ┆ 3    ┆ 3257   │
│ 2015   ┆ 4    ┆ 3143   │
│ 2015   ┆ 5    ┆ 3400   │
│ 2015   ┆ 6    ┆ 3378   │
│ 2015   ┆ 7    ┆ 3173   │
│ 2015   ┆ 8    ┆ 3353   │
│ 2015   ┆ 9    ┆ 3371   │
│ 2015   ┆ 10   ┆ 3235   │
└────────┴──────┴────────┘