In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [3]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2015   ┆ 1270   ┆ 67.444444 ┆ 72.074074   ┆ … ┆ 109.075583  ┆ 0.46737  ┆ 0.51851    ┆ 0.159417   │
│ 2021   ┆ 1193   ┆ 61.777778 ┆ 66.666667   ┆ … ┆ 100.155028  ┆ 0.454194 ┆ 0.495487   ┆ 0.179979   │
│ 2018   ┆ 1458   ┆ 66.848485 ┆ 65.969697   ┆ … ┆ 103.477457  ┆ 0.510626 ┆ 0.513067   ┆ 0.168469   │
│ 2023   ┆ 1331   ┆ 82.466667 ┆ 69.933333   ┆ … ┆ 97.714222   ┆ 0.562398 ┆ 0.488915   ┆ 0.123035   │
│ 2026   ┆ 1453   ┆ 73.869565 ┆ 78.173913   ┆ … ┆ 116.90346   ┆ 0.551634 ┆ 0.560615   ┆ 0.146306   │
│ 2016   ┆ 1304   ┆ 72.235294 ┆ 68.970588   ┆ … ┆ 102.364429  ┆ 0.503835 ┆ 0.501763   ┆ 0.173931   │
│ 2022   ┆ 1214   ┆ 63.153846 ┆ 70.730769   ┆ … ┆ 101.478071  ┆ 0.444615 ┆ 0.4776     ┆ 0.17027    │
│ 2016   ┆ 1127   ┆ 60.9      ┆ 68.633333   ┆ … ┆ 102.021101  ┆ 0.443719 ┆ 0.497673   ┆ 0.20524    │
│ 2017   ┆ 1284   ┆ 81.151515 ┆ 73.121212   ┆ … ┆ 97.707952   ┆ 0.509444 ┆ 0.471398   ┆ 0.166704   │
│ 2018   ┆ 1240   ┆ 70.59375  ┆ 65.625      ┆ … ┆ 97.425728   ┆ 0.506703 ┆ 0.482222   ┆ 0.190331   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [5]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [6]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [7]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2017   ┆ 1388   ┆ 72.5      ┆ 73.0        ┆ … ┆ 106.807446  ┆ 0.565741 ┆ 0.475867   ┆ 0.210036   │
│ 2025   ┆ 1384   ┆ 68.0      ┆ 70.0        ┆ … ┆ 106.221548  ┆ 0.604167 ┆ 0.492857   ┆ 0.225056   │
│ 2016   ┆ 1292   ┆ 70.0      ┆ 78.0        ┆ … ┆ 121.360419  ┆ 0.505959 ┆ 0.64503    ┆ 0.156102   │
│ 2021   ┆ 1159   ┆ 68.0      ┆ 85.0        ┆ … ┆ 107.902253  ┆ 0.5      ┆ 0.484615   ┆ 0.274742   │
│ 2016   ┆ 1425   ┆ 69.0      ┆ 70.0        ┆ … ┆ 105.026257  ┆ 0.596154 ┆ 0.475806   ┆ 0.18412    │
│ 2017   ┆ 1274   ┆ 58.0      ┆ 78.0        ┆ … ┆ 126.520681  ┆ 0.442308 ┆ 0.622642   ┆ 0.163733   │
│ 2024   ┆ 1242   ┆ 80.5      ┆ 89.0        ┆ … ┆ 121.61476   ┆ 0.552586 ┆ 0.596481   ┆ 0.162906   │
│ 2018   ┆ 1196   ┆ 71.5      ┆ 65.5        ┆ … ┆ 94.073396   ┆ 0.468376 ┆ 0.43874    ┆ 0.141917   │
│ 2015   ┆ 1138   ┆ 62.0      ┆ 68.0        ┆ … ┆ 104.897802  ┆ 0.522727 ┆ 0.5        ┆ 0.262042   │
│ 2025   ┆ 1251   ┆ 52.0      ┆ 81.0        ┆ … ┆ 120.490889  ┆ 0.393443 ┆ 0.631579   ┆ 0.176991   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [8]:
m_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneySeeds.csv")
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [9]:
m_tourney_seed_lf = m_tourney_seed_lf.with_columns(cs.numeric().exclude("Seed").cast(pl.Int16))
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [10]:
m_tourney_seed_lf = ecm.clean_seed(m_tourney_seed_lf)
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 1437   │
│ 2015   ┆ 2    ┆ 1438   │
│ 2015   ┆ 3    ┆ 1328   │
│ 2015   ┆ 4    ┆ 1257   │
│ 2015   ┆ 5    ┆ 1320   │
│ 2015   ┆ 6    ┆ 1344   │
│ 2015   ┆ 7    ┆ 1277   │
│ 2015   ┆ 8    ┆ 1301   │
│ 2015   ┆ 9    ┆ 1261   │
│ 2015   ┆ 10   ┆ 1208   │
└────────┴──────┴────────┘

In [11]:
m_golden_tabel_lf: pl.LazyFrame = ecm.merge_seed_with_regular(m_tourney_seed_lf, m_regular_season_detailed_lf)
m_golden_tabel_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2016   ┆ 1288   ┆ 67.433333 ┆ 72.033333     ┆ … ┆ 0.444618 ┆ 0.5076      ┆ 0.167122     ┆ null │
│ 2026   ┆ 1236   ┆ 74.571429 ┆ 79.285714     ┆ … ┆ 0.527078 ┆ 0.566426    ┆ 0.129594     ┆ null │
│ 2015   ┆ 1403   ┆ 60.90625  ┆ 64.34375      ┆ … ┆ 0.458624 ┆ 0.494786    ┆ 0.216168     ┆ null │
│ 2024   ┆ 1204   ┆ 73.333333 ┆ 79.242424     ┆ … ┆ 0.510739 ┆ 0.524112    ┆ 0.177879     ┆ null │
│ 2015   ┆ 1346   ┆ 69.733333 ┆ 67.533333     ┆ … ┆ 0.43979  ┆ 0.455848    ┆ 0.203991     ┆ null │
│ 2016   ┆ 1196   ┆ 73.606061 ┆ 68.575758     ┆ … ┆ 0.482738 ┆ 0.465163    ┆ 0.16232      ┆ null │
│ 2023   ┆ 1390   ┆ 70.333333 ┆ 68.363636     ┆ … ┆ 0.527038 ┆ 0.514864    ┆ 0.177114     ┆ null │
│ 2025   ┆ 1212   ┆ 64.419355 ┆ 69.290323     ┆ … ┆ 0.476853 ┆ 0.496743    ┆ 0.180867     ┆ null │
│ 2026   ┆ 1458   ┆ 83.227273 ┆ 75.045455     ┆ … ┆ 0.541258 ┆ 0.503061    ┆ 0.12917      ┆ null │
│ 2016   ┆ 1224   ┆ 70.233333 ┆ 76.333333     ┆ … ┆ 0.438039 ┆ 0.491299    ┆ 0.201317     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [12]:
del m_regular_season_detailed_lf, m_tourney_seed_lf

In [ ]:
m_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_matchups_lf = ecm.prepare_tourney_matchups(m_tourney_matchups_lf)
m_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ 1      │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ 1      │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ 1      │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ 1      │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ 1      │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ 1      │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ 1      │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ 1      │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ 1      │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

**Women's NCCA data**

In [14]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [15]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [16]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2017   ┆ 3409   ┆ 63.645161 ┆ 71.870968   ┆ … ┆ 100.545081  ┆ 0.443165 ┆ 0.467474   ┆ 0.201058   │
│ 2015   ┆ 3251   ┆ 67.25     ┆ 57.40625    ┆ … ┆ 84.008521   ┆ 0.457298 ┆ 0.39221    ┆ 0.240162   │
│ 2024   ┆ 3443   ┆ 63.322581 ┆ 64.290323   ┆ … ┆ 89.611704   ┆ 0.444948 ┆ 0.466775   ┆ 0.193536   │
│ 2018   ┆ 3273   ┆ 70.90625  ┆ 54.46875    ┆ … ┆ 81.652672   ┆ 0.478025 ┆ 0.424942   ┆ 0.137063   │
│ 2022   ┆ 3299   ┆ 67.931034 ┆ 66.758621   ┆ … ┆ 89.133182   ┆ 0.467851 ┆ 0.492969   ┆ 0.229079   │
│ 2019   ┆ 3162   ┆ 64.888889 ┆ 68.592593   ┆ … ┆ 96.913716   ┆ 0.46011  ┆ 0.453252   ┆ 0.212621   │
│ 2024   ┆ 3388   ┆ 60.3      ┆ 65.233333   ┆ … ┆ 97.219809   ┆ 0.494193 ┆ 0.484566   ┆ 0.220351   │
│ 2023   ┆ 3171   ┆ 53.714286 ┆ 69.321429   ┆ … ┆ 98.61973    ┆ 0.40471  ┆ 0.507532   ┆ 0.249268   │
│ 2015   ┆ 3230   ┆ 56.04     ┆ 68.8        ┆ … ┆ 98.804169   ┆ 0.405473 ┆ 0.495484   ┆ 0.261968   │
│ 2016   ┆ 3398   ┆ 61.214286 ┆ 69.357143   ┆ … ┆ 94.489629   ┆ 0.403475 ┆ 0.450888   ┆ 0.22661    │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [17]:
w_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [18]:
w_tourney_detailed_lf = w_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [19]:
w_tourney_detailed_lf = ecm.create_team_season_profile(w_tourney_detailed_lf)
w_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2017   ┆ 3417   ┆ 76.333333 ┆ 61.666667   ┆ … ┆ 94.271101   ┆ 0.593878 ┆ 0.438825   ┆ 0.146061   │
│ 2021   ┆ 3180   ┆ 53.0      ┆ 67.0        ┆ … ┆ 100.75188   ┆ 0.386364 ┆ 0.448276   ┆ 0.172009   │
│ 2021   ┆ 3372   ┆ 52.0      ┆ 54.0        ┆ … ┆ 81.725312   ┆ 0.333333 ┆ 0.354839   ┆ 0.153417   │
│ 2023   ┆ 3208   ┆ 66.0      ┆ 64.0        ┆ … ┆ 82.480882   ┆ 0.453161 ┆ 0.440041   ┆ 0.22355    │
│ 2021   ┆ 3257   ┆ 64.75     ┆ 54.0        ┆ … ┆ 80.119593   ┆ 0.466931 ┆ 0.371442   ┆ 0.178728   │
│ 2017   ┆ 3199   ┆ 73.5      ┆ 61.25       ┆ … ┆ 83.04865    ┆ 0.459989 ┆ 0.469946   ┆ 0.187637   │
│ 2024   ┆ 3276   ┆ 72.0      ┆ 81.0        ┆ … ┆ 111.878453  ┆ 0.5      ┆ 0.54386    ┆ 0.156352   │
│ 2022   ┆ 3174   ┆ 71.0      ┆ 102.0       ┆ … ┆ 141.519251  ┆ 0.403846 ┆ 0.671875   ┆ 0.126143   │
│ 2024   ┆ 3417   ┆ 73.333333 ┆ 65.333333   ┆ … ┆ 89.951055   ┆ 0.4632   ┆ 0.437754   ┆ 0.196321   │
│ 2025   ┆ 3261   ┆ 87.25     ┆ 66.0        ┆ … ┆ 86.887481   ┆ 0.503697 ┆ 0.417284   ┆ 0.163674   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [20]:
w_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneySeeds.csv")
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [21]:
w_tourney_seed_lf = w_tourney_seed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [22]:
w_tourney_seed_lf = ecm.clean_seed(w_tourney_seed_lf)
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 3163   │
│ 2015   ┆ 2    ┆ 3246   │
│ 2015   ┆ 3    ┆ 3257   │
│ 2015   ┆ 4    ┆ 3143   │
│ 2015   ┆ 5    ┆ 3400   │
│ 2015   ┆ 6    ┆ 3378   │
│ 2015   ┆ 7    ┆ 3173   │
│ 2015   ┆ 8    ┆ 3353   │
│ 2015   ┆ 9    ┆ 3371   │
│ 2015   ┆ 10   ┆ 3235   │
└────────┴──────┴────────┘

In [23]:
w_golden_table_lf: pl.LazyFrame = ecm.merge_seed_with_regular(w_tourney_seed_lf, w_regular_season_detailed_lf)
w_golden_table_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2017   ┆ 3219   ┆ 67.25     ┆ 66.5          ┆ … ┆ 0.452538 ┆ 0.457314    ┆ 0.217951     ┆ null │
│ 2016   ┆ 3253   ┆ 62.5625   ┆ 59.375        ┆ … ┆ 0.448425 ┆ 0.447085    ┆ 0.230082     ┆ null │
│ 2026   ┆ 3394   ┆ 56.421053 ┆ 70.315789     ┆ … ┆ 0.439938 ┆ 0.456046    ┆ 0.278128     ┆ null │
│ 2022   ┆ 3197   ┆ 53.962963 ┆ 73.888889     ┆ … ┆ 0.379542 ┆ 0.490206    ┆ 0.254258     ┆ null │
│ 2026   ┆ 3138   ┆ 58.954545 ┆ 72.545455     ┆ … ┆ 0.407836 ┆ 0.479733    ┆ 0.260588     ┆ null │
│ 2023   ┆ 3111   ┆ 65.758621 ┆ 70.862069     ┆ … ┆ 0.440401 ┆ 0.469068    ┆ 0.201778     ┆ null │
│ 2019   ┆ 3339   ┆ 72.821429 ┆ 78.035714     ┆ … ┆ 0.479758 ┆ 0.498946    ┆ 0.213784     ┆ null │
│ 2021   ┆ 3161   ┆ 74.894737 ┆ 67.263158     ┆ … ┆ 0.49249  ┆ 0.441452    ┆ 0.136373     ┆ null │
│ 2015   ┆ 3181   ┆ 70.774194 ┆ 59.129032     ┆ … ┆ 0.481425 ┆ 0.406615    ┆ 0.254566     ┆ 4    │
│ 2017   ┆ 3435   ┆ 68.7      ┆ 71.133333     ┆ … ┆ 0.471187 ┆ 0.455602    ┆ 0.250766     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [24]:
del w_tourney_seed_lf, w_regular_season_detailed_lf

In [25]:
w_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_matchups_lf = ecm.prepare_tourney_matchups(w_tourney_matchups_lf)
w_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ 1      │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ 1      │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ 1      │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ 1      │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ 1      │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ 1      │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ 1      │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ 1      │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ 1      │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘