In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [3]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2023   ┆ 1293   ┆ 69.806452 ┆ 72.645161   ┆ … ┆ 106.875342  ┆ 0.492138 ┆ 0.524092   ┆ 0.152652   │
│ 2018   ┆ 1236   ┆ 79.392857 ┆ 77.392857   ┆ … ┆ 104.174911  ┆ 0.529369 ┆ 0.537126   ┆ 0.158312   │
│ 2021   ┆ 1309   ┆ 76.041667 ┆ 77.208333   ┆ … ┆ 101.355144  ┆ 0.522968 ┆ 0.516744   ┆ 0.210357   │
│ 2022   ┆ 1342   ┆ 65.206897 ┆ 70.034483   ┆ … ┆ 102.669912  ┆ 0.45546  ┆ 0.54055    ┆ 0.183073   │
│ 2016   ┆ 1229   ┆ 66.967742 ┆ 66.16129    ┆ … ┆ 97.363813   ┆ 0.483409 ┆ 0.486627   ┆ 0.184264   │
│ 2015   ┆ 1299   ┆ 57.833333 ┆ 66.566667   ┆ … ┆ 106.385876  ┆ 0.44957  ┆ 0.503404   ┆ 0.231215   │
│ 2021   ┆ 1150   ┆ 63.125    ┆ 66.375      ┆ … ┆ 100.571025  ┆ 0.492444 ┆ 0.511805   ┆ 0.191282   │
│ 2017   ┆ 1150   ┆ 75.655172 ┆ 79.965517   ┆ … ┆ 107.265456  ┆ 0.504163 ┆ 0.524156   ┆ 0.16169    │
│ 2019   ┆ 1405   ┆ 76.580645 ┆ 68.387097   ┆ … ┆ 97.324367   ┆ 0.53729  ┆ 0.46931    ┆ 0.174729   │
│ 2025   ┆ 1477   ┆ 64.354839 ┆ 74.870968   ┆ … ┆ 108.709336  ┆ 0.493541 ┆ 0.542093   ┆ 0.210441   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [5]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [6]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [7]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬────────────┬───────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficie ┆ TeamEFG   ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ ncy        ┆ ---       ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---        ┆ f64       ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64        ┆           ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ 2018   ┆ 1361   ┆ 65.0      ┆ 67.0        ┆ … ┆ 95.170455  ┆ 0.407407  ┆ 0.415254   ┆ 0.167539   │
│ 2016   ┆ 1138   ┆ 72.0      ┆ 79.0        ┆ … ┆ 107.997266 ┆ 0.474576  ┆ 0.490741   ┆ 0.139958   │
│ 2015   ┆ 1140   ┆ 90.0      ┆ 94.0        ┆ … ┆ 114.739091 ┆ 0.612069  ┆ 0.49375    ┆ 0.187911   │
│ 2021   ┆ 1196   ┆ 76.5      ┆ 75.5        ┆ … ┆ 103.413251 ┆ 0.615817  ┆ 0.513158   ┆ 0.242259   │
│ 2023   ┆ 1301   ┆ 63.0      ┆ 72.0        ┆ … ┆ 101.372756 ┆ 0.3984375 ┆ 0.491071   ┆ 0.086799   │
│ 2024   ┆ 1286   ┆ 81.0      ┆ 88.0        ┆ … ┆ 112.929098 ┆ 0.62931   ┆ 0.530303   ┆ 0.142602   │
│ 2016   ┆ 1435   ┆ 50.0      ┆ 70.0        ┆ … ┆ 101.633394 ┆ 0.330189  ┆ 0.432203   ┆ 0.175567   │
│ 2023   ┆ 1394   ┆ 75.0      ┆ 83.5        ┆ … ┆ 113.029581 ┆ 0.407193  ┆ 0.561216   ┆ 0.133269   │
│ 2017   ┆ 1314   ┆ 81.666667 ┆ 70.5        ┆ … ┆ 95.5359    ┆ 0.484142  ┆ 0.456778   ┆ 0.152657   │
│ 2025   ┆ 1257   ┆ 75.0      ┆ 89.0        ┆ … ┆ 127.188282 ┆ 0.485714  ┆ 0.669643   ┆ 0.084746   │
└────────┴────────┴───────────┴─────────────┴───┴────────────┴───────────┴────────────┴────────────┘

In [8]:
m_tourney_detailed_df: pl.DataFrame = m_tourney_detailed_lf.collect()
m_tourney_detailed_df.write_parquet("../data/proccessed/m_tourney_detailed.parquet")

In [9]:
del m_tourney_detailed_df, m_tourney_detailed_lf

In [10]:
m_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneySeeds.csv")
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [11]:
m_tourney_seed_lf = m_tourney_seed_lf.with_columns(cs.numeric().exclude("Seed").cast(pl.Int16))
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [12]:
m_tourney_seed_lf = ecm.clean_seed(m_tourney_seed_lf)
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 1437   │
│ 2015   ┆ 2    ┆ 1438   │
│ 2015   ┆ 3    ┆ 1328   │
│ 2015   ┆ 4    ┆ 1257   │
│ 2015   ┆ 5    ┆ 1320   │
│ 2015   ┆ 6    ┆ 1344   │
│ 2015   ┆ 7    ┆ 1277   │
│ 2015   ┆ 8    ┆ 1301   │
│ 2015   ┆ 9    ┆ 1261   │
│ 2015   ┆ 10   ┆ 1208   │
└────────┴──────┴────────┘

In [13]:
m_golden_tabel_lf: pl.LazyFrame = ecm.merge_seed_with_regular(m_tourney_seed_lf, m_regular_season_detailed_lf)
m_golden_tabel_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2019   ┆ 1201   ┆ 76.032258 ┆ 67.709677     ┆ … ┆ 0.54562  ┆ 0.48653     ┆ 0.180948     ┆ null │
│ 2019   ┆ 1274   ┆ 71.78125  ┆ 71.09375      ┆ … ┆ 0.509352 ┆ 0.522515    ┆ 0.168426     ┆ null │
│ 2025   ┆ 1224   ┆ 75.571429 ┆ 80.714286     ┆ … ┆ 0.538531 ┆ 0.522977    ┆ 0.196783     ┆ null │
│ 2025   ┆ 1239   ┆ 71.4      ┆ 71.366667     ┆ … ┆ 0.502397 ┆ 0.512349    ┆ 0.179682     ┆ null │
│ 2018   ┆ 1374   ┆ 69.484848 ┆ 64.060606     ┆ … ┆ 0.522082 ┆ 0.495631    ┆ 0.180434     ┆ null │
│ 2019   ┆ 1312   ┆ 69.90625  ┆ 68.6875       ┆ … ┆ 0.510305 ┆ 0.48964     ┆ 0.176261     ┆ null │
│ 2015   ┆ 1232   ┆ 66.066667 ┆ 67.766667     ┆ … ┆ 0.494915 ┆ 0.492602    ┆ 0.20886      ┆ null │
│ 2017   ┆ 1243   ┆ 71.727273 ┆ 66.939394     ┆ … ┆ 0.525755 ┆ 0.488951    ┆ 0.191927     ┆ 11   │
│ 2021   ┆ 1408   ┆ 63.913043 ┆ 66.478261     ┆ … ┆ 0.444919 ┆ 0.496014    ┆ 0.148562     ┆ null │
│ 2016   ┆ 1283   ┆ 66.967742 ┆ 73.064516     ┆ … ┆ 0.462634 ┆ 0.514719    ┆ 0.185708     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [14]:
del m_regular_season_detailed_lf, m_tourney_seed_lf

In [15]:
m_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_matchups_lf = ecm.prepare_tourney_matchups(m_tourney_matchups_lf)
m_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ 1      │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ 1      │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ 1      │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ 1      │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ 1      │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ 1      │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ 1      │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ 1      │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ 1      │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

In [16]:
m_train_data_lf: pl.LazyFrame = ecm.finalize_training_data(m_tourney_matchups_lf, m_golden_tabel_lf)
m_train_data_lf.head(10).collect()

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ … ┆ -0.040666    ┆ -0.014806    ┆ -0.007078    ┆ 0         │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ … ┆ -0.047807    ┆ -0.024097    ┆ 0.002589     ┆ 0         │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ … ┆ -0.008537    ┆ -0.001035    ┆ 0.017282     ┆ 0         │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ … ┆ -0.02873     ┆ 0.003899     ┆ 0.022644     ┆ 0         │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ … ┆ 0.037546     ┆ -0.04521     ┆ -0.031617    ┆ -13       │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ … ┆ -0.016964    ┆ 0.01076      ┆ -0.006101    ┆ -7        │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ … ┆ -0.000487    ┆ 0.047622     ┆ -0.024455    ┆ -5        │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ … ┆ -0.000502    ┆ -0.007881    ┆ 0.014252     ┆ -1        │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ … ┆ -0.044199    ┆ -0.053542    ┆ 0.032444     ┆ -9        │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ … ┆ 0.021938     ┆ -0.013491    ┆ -0.030793    ┆ 11        │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [17]:
del m_tourney_matchups_lf, m_golden_tabel_lf

In [18]:
m_train_data_df: pl.DataFrame = m_train_data_lf.collect()
m_train_data_df.write_parquet("../data/proccessed/m_train_data.parquet")

In [19]:
del m_train_data_df, m_train_data_lf

**Women's NCCA data**

In [20]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [21]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [22]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2023   ┆ 3427   ┆ 64.78125  ┆ 67.3125     ┆ … ┆ 93.025064   ┆ 0.445421 ┆ 0.457828   ┆ 0.237858   │
│ 2017   ┆ 3337   ┆ 60.8      ┆ 69.8        ┆ … ┆ 97.392307   ┆ 0.410793 ┆ 0.436827   ┆ 0.232652   │
│ 2024   ┆ 3408   ┆ 64.375    ┆ 65.5625     ┆ … ┆ 94.326412   ┆ 0.485829 ┆ 0.471267   ┆ 0.223173   │
│ 2017   ┆ 3355   ┆ 70.133333 ┆ 59.466667   ┆ … ┆ 87.208644   ┆ 0.497457 ┆ 0.43471    ┆ 0.196662   │
│ 2018   ┆ 3377   ┆ 72.62069  ┆ 60.655172   ┆ … ┆ 89.375515   ┆ 0.534702 ┆ 0.479029   ┆ 0.1861     │
│ 2021   ┆ 3249   ┆ 61.833333 ┆ 67.5        ┆ … ┆ 91.119195   ┆ 0.413821 ┆ 0.483412   ┆ 0.203698   │
│ 2023   ┆ 3312   ┆ 60.517241 ┆ 63.827586   ┆ … ┆ 92.646913   ┆ 0.45633  ┆ 0.454625   ┆ 0.225568   │
│ 2018   ┆ 3308   ┆ 65.75     ┆ 66.142857   ┆ … ┆ 94.115968   ┆ 0.476576 ┆ 0.457666   ┆ 0.210491   │
│ 2019   ┆ 3189   ┆ 61.275862 ┆ 69.448276   ┆ … ┆ 98.641761   ┆ 0.429843 ┆ 0.486371   ┆ 0.255892   │
│ 2021   ┆ 3180   ┆ 61.545455 ┆ 57.318182   ┆ … ┆ 86.278291   ┆ 0.456386 ┆ 0.436715   ┆ 0.167276   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [23]:
w_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [24]:
w_tourney_detailed_lf = w_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [25]:
w_tourney_detailed_lf = ecm.create_team_season_profile(w_tourney_detailed_lf)
w_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2023   ┆ 3328   ┆ 79.0      ┆ 72.5        ┆ … ┆ 91.430206   ┆ 0.472783 ┆ 0.446509   ┆ 0.209954   │
│ 2023   ┆ 3339   ┆ 63.0      ┆ 85.0        ┆ … ┆ 108.418367  ┆ 0.401639 ┆ 0.471429   ┆ 0.217879   │
│ 2025   ┆ 3279   ┆ 71.333333 ┆ 68.0        ┆ … ┆ 92.589154   ┆ 0.390678 ┆ 0.519066   ┆ 0.123807   │
│ 2015   ┆ 3443   ┆ 64.0      ┆ 66.0        ┆ … ┆ 96.809681   ┆ 0.421875 ┆ 0.483051   ┆ 0.126538   │
│ 2016   ┆ 3113   ┆ 69.0      ┆ 63.5        ┆ … ┆ 94.537743   ┆ 0.522673 ┆ 0.450893   ┆ 0.229496   │
│ 2017   ┆ 3257   ┆ 73.333333 ┆ 74.333333   ┆ … ┆ 103.750325  ┆ 0.503972 ┆ 0.460714   ┆ 0.162313   │
│ 2022   ┆ 3211   ┆ 63.5      ┆ 61.5        ┆ … ┆ 94.97781    ┆ 0.464464 ┆ 0.427455   ┆ 0.227866   │
│ 2024   ┆ 3242   ┆ 68.0      ┆ 72.5        ┆ … ┆ 94.884506   ┆ 0.463894 ┆ 0.485075   ┆ 0.192286   │
│ 2019   ┆ 3120   ┆ 64.0      ┆ 73.0        ┆ … ┆ 94.193548   ┆ 0.346667 ┆ 0.516949   ┆ 0.147651   │
│ 2024   ┆ 3166   ┆ 75.0      ┆ 70.0        ┆ … ┆ 104.840567  ┆ 0.559553 ┆ 0.515038   ┆ 0.125375   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [26]:
w_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneySeeds.csv")
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [27]:
w_tourney_seed_lf = w_tourney_seed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [28]:
w_tourney_seed_lf = ecm.clean_seed(w_tourney_seed_lf)
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 3163   │
│ 2015   ┆ 2    ┆ 3246   │
│ 2015   ┆ 3    ┆ 3257   │
│ 2015   ┆ 4    ┆ 3143   │
│ 2015   ┆ 5    ┆ 3400   │
│ 2015   ┆ 6    ┆ 3378   │
│ 2015   ┆ 7    ┆ 3173   │
│ 2015   ┆ 8    ┆ 3353   │
│ 2015   ┆ 9    ┆ 3371   │
│ 2015   ┆ 10   ┆ 3235   │
└────────┴──────┴────────┘

In [29]:
w_golden_table_lf: pl.LazyFrame = ecm.merge_seed_with_regular(w_tourney_seed_lf, w_regular_season_detailed_lf)
w_golden_table_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2022   ┆ 3456   ┆ 56.172414 ┆ 64.931034     ┆ … ┆ 0.448624 ┆ 0.468372    ┆ 0.262496     ┆ null │
│ 2024   ┆ 3462   ┆ 50.714286 ┆ 72.642857     ┆ … ┆ 0.420328 ┆ 0.513675    ┆ 0.256405     ┆ null │
│ 2026   ┆ 3349   ┆ 69.590909 ┆ 58.636364     ┆ … ┆ 0.451551 ┆ 0.4127      ┆ 0.186402     ┆ null │
│ 2019   ┆ 3412   ┆ 73.0      ┆ 58.466667     ┆ … ┆ 0.522732 ┆ 0.405707    ┆ 0.166782     ┆ null │
│ 2016   ┆ 3114   ┆ 59.28125  ┆ 55.0          ┆ … ┆ 0.458198 ┆ 0.442931    ┆ 0.24479      ┆ null │
│ 2015   ┆ 3385   ┆ 62.870968 ┆ 58.258065     ┆ … ┆ 0.450874 ┆ 0.428692    ┆ 0.206287     ┆ null │
│ 2017   ┆ 3354   ┆ 54.923077 ┆ 65.846154     ┆ … ┆ 0.364558 ┆ 0.429703    ┆ 0.269729     ┆ null │
│ 2016   ┆ 3158   ┆ 55.548387 ┆ 61.645161     ┆ … ┆ 0.401128 ┆ 0.431012    ┆ 0.241249     ┆ null │
│ 2019   ┆ 3208   ┆ 68.366667 ┆ 60.066667     ┆ … ┆ 0.47503  ┆ 0.416582    ┆ 0.225565     ┆ null │
│ 2019   ┆ 3304   ┆ 72.366667 ┆ 70.066667     ┆ … ┆ 0.487927 ┆ 0.463908    ┆ 0.204685     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [30]:
del w_tourney_seed_lf, w_regular_season_detailed_lf

In [31]:
w_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_matchups_lf = ecm.prepare_tourney_matchups(w_tourney_matchups_lf)
w_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ 1      │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ 1      │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ 1      │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ 1      │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ 1      │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ 1      │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ 1      │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ 1      │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ 1      │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

In [32]:
w_train_data_lf: pl.LazyFrame = ecm.finalize_training_data(w_tourney_matchups_lf, w_golden_table_lf)
w_train_data_lf.head(10).collect()

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ … ┆ -0.065267    ┆ -0.022153    ┆ 0.002366     ┆ 3         │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ … ┆ 0.06781      ┆ -0.053646    ┆ -0.008088    ┆ -13       │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ … ┆ 0.002632     ┆ 0.000894     ┆ 0.012675     ┆ -9        │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ … ┆ 0.010844     ┆ -0.037637    ┆ 0.030525     ┆ -3        │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ … ┆ 0.028656     ┆ 0.038958     ┆ -0.047683    ┆ 1         │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ … ┆ -0.018015    ┆ -0.041011    ┆ 0.009153     ┆ -9        │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ … ┆ 0.030676     ┆ 0.016624     ┆ 0.003185     ┆ 5         │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ … ┆ 0.03694      ┆ 0.048403     ┆ -0.012815    ┆ -11       │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ … ┆ 0.001469     ┆ -0.000361    ┆ -0.013834    ┆ -13       │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ … ┆ -0.047435    ┆ -0.002718    ┆ 0.041146     ┆ 5         │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [33]:
del w_tourney_matchups_lf, w_golden_table_lf