In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [ ]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2019   ┆ 1454   ┆ 68.633333 ┆ 75.033333   ┆ … ┆ 108.848106  ┆ 0.484263 ┆ 0.516941   ┆ 0.180068   │
│ 2021   ┆ 1376   ┆ 72.52381  ┆ 79.142857   ┆ … ┆ 104.45182   ┆ 0.466523 ┆ 0.531085   ┆ 0.188807   │
│ 2015   ┆ 1377   ┆ 69.0      ┆ 70.419355   ┆ … ┆ 104.996401  ┆ 0.471    ┆ 0.515541   ┆ 0.165926   │
│ 2021   ┆ 1245   ┆ 76.090909 ┆ 72.454545   ┆ … ┆ 100.331787  ┆ 0.507831 ┆ 0.498461   ┆ 0.186229   │
│ 2023   ┆ 1231   ┆ 75.030303 ┆ 68.454545   ┆ … ┆ 99.38492    ┆ 0.537395 ┆ 0.473132   ┆ 0.159535   │
│ 2024   ┆ 1467   ┆ 67.774194 ┆ 64.580645   ┆ … ┆ 93.314881   ┆ 0.500603 ┆ 0.462206   ┆ 0.175792   │
│ 2019   ┆ 1310   ┆ 72.4375   ┆ 76.0        ┆ … ┆ 108.332352  ┆ 0.495355 ┆ 0.536513   ┆ 0.171434   │
│ 2024   ┆ 1311   ┆ 73.16129  ┆ 74.935484   ┆ … ┆ 104.658854  ┆ 0.513676 ┆ 0.500597   ┆ 0.174141   │
│ 2022   ┆ 1457   ┆ 73.655172 ┆ 71.586207   ┆ … ┆ 101.541966  ┆ 0.561438 ┆ 0.510875   ┆ 0.199672   │
│ 2017   ┆ 1166   ┆ 81.545455 ┆ 72.606061   ┆ … ┆ 100.917397  ┆ 0.580181 ┆ 0.501499   ┆ 0.170897   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [5]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [7]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [8]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2019   ┆ 1233   ┆ 73.0      ┆ 88.0        ┆ … ┆ 118.718381  ┆ 0.536364 ┆ 0.513333   ┆ 0.166378   │
│ 2015   ┆ 1372   ┆ 50.0      ┆ 57.0        ┆ … ┆ 93.480935   ┆ 0.382353 ┆ 0.539474   ┆ 0.206274   │
│ 2025   ┆ 1361   ┆ 68.0      ┆ 95.0        ┆ … ┆ 136.887608  ┆ 0.465517 ┆ 0.649123   ┆ 0.155093   │
│ 2015   ┆ 1345   ┆ 65.0      ┆ 66.0        ┆ … ┆ 95.686843   ┆ 0.388889 ┆ 0.442623   ┆ 0.171123   │
│ 2019   ┆ 1295   ┆ 70.0      ┆ 79.5        ┆ … ┆ 120.476597  ┆ 0.499171 ┆ 0.534615   ┆ 0.139579   │
│ 2015   ┆ 1116   ┆ 67.0      ┆ 70.0        ┆ … ┆ 102.028895  ┆ 0.460176 ┆ 0.430263   ┆ 0.220012   │
│ 2023   ┆ 1158   ┆ 57.0      ┆ 63.0        ┆ … ┆ 86.836664   ┆ 0.366071 ┆ 0.464286   ┆ 0.149198   │
│ 2019   ┆ 1246   ┆ 68.5      ┆ 58.75       ┆ … ┆ 91.143326   ┆ 0.502367 ┆ 0.432616   ┆ 0.188739   │
│ 2023   ┆ 1345   ┆ 58.0      ┆ 63.0        ┆ … ┆ 95.81749    ┆ 0.40566  ┆ 0.443548   ┆ 0.238717   │
│ 2016   ┆ 1221   ┆ 55.5      ┆ 73.0        ┆ … ┆ 112.373668  ┆ 0.490341 ┆ 0.5131     ┆ 0.19268    │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

**Women's NCCA data**

In [9]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [ ]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

In [ ]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()