In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [3]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2023   ┆ 1407   ┆ 70.433333 ┆ 67.8        ┆ … ┆ 98.256274   ┆ 0.495325 ┆ 0.4866     ┆ 0.174829   │
│ 2017   ┆ 1370   ┆ 68.259259 ┆ 72.666667   ┆ … ┆ 100.816959  ┆ 0.513494 ┆ 0.476897   ┆ 0.208037   │
│ 2017   ┆ 1352   ┆ 64.393939 ┆ 67.818182   ┆ … ┆ 96.052454   ┆ 0.451356 ┆ 0.485756   ┆ 0.216275   │
│ 2018   ┆ 1245   ┆ 72.484848 ┆ 74.454545   ┆ … ┆ 106.007342  ┆ 0.486617 ┆ 0.515999   ┆ 0.185248   │
│ 2023   ┆ 1149   ┆ 70.413793 ┆ 75.37931    ┆ … ┆ 112.495935  ┆ 0.504276 ┆ 0.543892   ┆ 0.172233   │
│ 2021   ┆ 1394   ┆ 63.428571 ┆ 74.095238   ┆ … ┆ 103.149999  ┆ 0.468587 ┆ 0.517183   ┆ 0.227457   │
│ 2024   ┆ 1371   ┆ 72.78125  ┆ 70.15625    ┆ … ┆ 102.015514  ┆ 0.503128 ┆ 0.495531   ┆ 0.174695   │
│ 2016   ┆ 1412   ┆ 77.774194 ┆ 70.419355   ┆ … ┆ 100.585664  ┆ 0.538101 ┆ 0.482803   ┆ 0.178061   │
│ 2019   ┆ 1391   ┆ 67.689655 ┆ 79.241379   ┆ … ┆ 111.201593  ┆ 0.457051 ┆ 0.545174   ┆ 0.175488   │
│ 2016   ┆ 1227   ┆ 65.428571 ┆ 79.142857   ┆ … ┆ 107.580688  ┆ 0.414907 ┆ 0.496621   ┆ 0.212131   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [5]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [6]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [7]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2019   ┆ 1234   ┆ 78.0      ┆ 77.5        ┆ … ┆ 109.402225  ┆ 0.550048 ┆ 0.505128   ┆ 0.185518   │
│ 2018   ┆ 1401   ┆ 77.0      ┆ 77.666667   ┆ … ┆ 108.419348  ┆ 0.552564 ┆ 0.528608   ┆ 0.193192   │
│ 2018   ┆ 1345   ┆ 71.666667 ┆ 66.333333   ┆ … ┆ 101.599425  ┆ 0.526831 ┆ 0.487468   ┆ 0.181869   │
│ 2017   ┆ 1305   ┆ 73.0      ┆ 84.0        ┆ … ┆ 122.538293  ┆ 0.461538 ┆ 0.62963    ┆ 0.100575   │
│ 2024   ┆ 1196   ┆ 100.0     ┆ 102.0       ┆ … ┆ 136.591898  ┆ 0.595588 ┆ 0.685185   ┆ 0.104644   │
│ 2025   ┆ 1246   ┆ 75.0      ┆ 70.0        ┆ … ┆ 105.452347  ┆ 0.545918 ┆ 0.491132   ┆ 0.134903   │
│ 2022   ┆ 1353   ┆ 87.0      ┆ 89.0        ┆ … ┆ 114.690722  ┆ 0.584507 ┆ 0.555556   ┆ 0.176032   │
│ 2022   ┆ 1308   ┆ 59.0      ┆ 58.0        ┆ … ┆ 88.881393   ┆ 0.483113 ┆ 0.401961   ┆ 0.182447   │
│ 2023   ┆ 1228   ┆ 63.0      ┆ 73.0        ┆ … ┆ 93.860495   ┆ 0.442308 ┆ 0.404762   ┆ 0.204212   │
│ 2024   ┆ 1173   ┆ 65.5      ┆ 69.0        ┆ … ┆ 100.103541  ┆ 0.50479  ┆ 0.547576   ┆ 0.188533   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [8]:
m_tourney_detailed_df: pl.DataFrame = m_tourney_detailed_lf.collect()
m_tourney_detailed_df.write_parquet("../data/proccessed/m_tourney_detailed.parquet")

In [9]:
del m_tourney_detailed_df, m_tourney_detailed_lf

In [10]:
m_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneySeeds.csv")
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [11]:
m_tourney_seed_lf = m_tourney_seed_lf.with_columns(cs.numeric().exclude("Seed").cast(pl.Int16))
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [12]:
m_tourney_seed_lf = ecm.clean_seed(m_tourney_seed_lf)
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 1437   │
│ 2015   ┆ 2    ┆ 1438   │
│ 2015   ┆ 3    ┆ 1328   │
│ 2015   ┆ 4    ┆ 1257   │
│ 2015   ┆ 5    ┆ 1320   │
│ 2015   ┆ 6    ┆ 1344   │
│ 2015   ┆ 7    ┆ 1277   │
│ 2015   ┆ 8    ┆ 1301   │
│ 2015   ┆ 9    ┆ 1261   │
│ 2015   ┆ 10   ┆ 1208   │
└────────┴──────┴────────┘

In [13]:
m_golden_tabel_lf: pl.LazyFrame = ecm.merge_seed_with_regular(m_tourney_seed_lf, m_regular_season_detailed_lf)
m_golden_tabel_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2022   ┆ 1136   ┆ 76.433333 ┆ 73.366667     ┆ … ┆ 0.498844 ┆ 0.474439    ┆ 0.177211     ┆ 16   │
│ 2023   ┆ 1282   ┆ 63.033333 ┆ 69.533333     ┆ … ┆ 0.438536 ┆ 0.504152    ┆ 0.181494     ┆ null │
│ 2023   ┆ 1419   ┆ 63.448276 ┆ 71.517241     ┆ … ┆ 0.453656 ┆ 0.518771    ┆ 0.170341     ┆ null │
│ 2017   ┆ 1193   ┆ 72.266667 ┆ 73.033333     ┆ … ┆ 0.510714 ┆ 0.491335    ┆ 0.185844     ┆ null │
│ 2023   ┆ 1356   ┆ 65.03125  ┆ 61.71875      ┆ … ┆ 0.517616 ┆ 0.478049    ┆ 0.178194     ┆ null │
│ 2026   ┆ 1241   ┆ 74.043478 ┆ 76.086957     ┆ … ┆ 0.531245 ┆ 0.498412    ┆ 0.158216     ┆ null │
│ 2017   ┆ 1261   ┆ 74.806452 ┆ 82.967742     ┆ … ┆ 0.50431  ┆ 0.545286    ┆ 0.198337     ┆ null │
│ 2017   ┆ 1245   ┆ 75.911765 ┆ 72.823529     ┆ … ┆ 0.481865 ┆ 0.498166    ┆ 0.179881     ┆ 14   │
│ 2023   ┆ 1408   ┆ 79.935484 ┆ 77.16129      ┆ … ┆ 0.523004 ┆ 0.505816    ┆ 0.143299     ┆ null │
│ 2018   ┆ 1377   ┆ 79.633333 ┆ 70.133333     ┆ … ┆ 0.52877  ┆ 0.48447     ┆ 0.15832      ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [14]:
del m_regular_season_detailed_lf, m_tourney_seed_lf

In [15]:
m_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_matchups_lf = ecm.prepare_tourney_matchups(m_tourney_matchups_lf)
m_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ 1      │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ 1      │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ 1      │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ 1      │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ 1      │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ 1      │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ 1      │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ 1      │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ 1      │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

In [16]:
m_train_data_lf: pl.LazyFrame = ecm.finalize_training_data(m_tourney_matchups_lf, m_golden_tabel_lf)
m_train_data_lf.head(10).collect()

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ … ┆ -0.040666    ┆ -0.014806    ┆ -0.007078    ┆ 0         │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ … ┆ -0.047807    ┆ -0.024097    ┆ 0.002589     ┆ 0         │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ … ┆ -0.008537    ┆ -0.001035    ┆ 0.017282     ┆ 0         │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ … ┆ -0.02873     ┆ 0.003899     ┆ 0.022644     ┆ 0         │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ … ┆ 0.037546     ┆ -0.04521     ┆ -0.031617    ┆ -13       │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ … ┆ -0.016964    ┆ 0.01076      ┆ -0.006101    ┆ -7        │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ … ┆ -0.000487    ┆ 0.047622     ┆ -0.024455    ┆ -5        │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ … ┆ -0.000502    ┆ -0.007881    ┆ 0.014252     ┆ -1        │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ … ┆ -0.044199    ┆ -0.053542    ┆ 0.032444     ┆ -9        │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ … ┆ 0.021938     ┆ -0.013491    ┆ -0.030793    ┆ 11        │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [17]:
del m_tourney_matchups_lf, m_golden_tabel_lf

In [18]:
m_train_data_df: pl.DataFrame = m_train_data_lf.collect()
m_train_data_df.write_parquet("../data/proccessed/m_train_data.parquet")

In [19]:
del m_train_data_df, m_train_data_lf

**Women's NCCA data**

In [20]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [21]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [22]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2017   ┆ 3209   ┆ 60.206897 ┆ 63.965517   ┆ … ┆ 91.000834   ┆ 0.424067 ┆ 0.454222   ┆ 0.263307   │
│ 2017   ┆ 3378   ┆ 70.9375   ┆ 61.625      ┆ … ┆ 90.436434   ┆ 0.48733  ┆ 0.437052   ┆ 0.193838   │
│ 2017   ┆ 3271   ┆ 60.285714 ┆ 64.857143   ┆ … ┆ 92.858845   ┆ 0.417706 ┆ 0.435447   ┆ 0.215481   │
│ 2018   ┆ 3429   ┆ 57.931034 ┆ 67.965517   ┆ … ┆ 101.250694  ┆ 0.423239 ┆ 0.489759   ┆ 0.237488   │
│ 2021   ┆ 3220   ┆ 59.65     ┆ 65.3        ┆ … ┆ 89.742076   ┆ 0.410099 ┆ 0.463174   ┆ 0.243995   │
│ 2018   ┆ 3137   ┆ 63.612903 ┆ 57.387097   ┆ … ┆ 83.379921   ┆ 0.466975 ┆ 0.409195   ┆ 0.254826   │
│ 2019   ┆ 3116   ┆ 72.647059 ┆ 69.705882   ┆ … ┆ 93.735339   ┆ 0.452813 ┆ 0.46175    ┆ 0.154903   │
│ 2015   ┆ 3211   ┆ 71.354839 ┆ 61.096774   ┆ … ┆ 87.431026   ┆ 0.491255 ┆ 0.420098   ┆ 0.240991   │
│ 2024   ┆ 3408   ┆ 64.375    ┆ 65.5625     ┆ … ┆ 94.326412   ┆ 0.485829 ┆ 0.471267   ┆ 0.223173   │
│ 2016   ┆ 3108   ┆ 60.928571 ┆ 67.785714   ┆ … ┆ 89.924223   ┆ 0.384324 ┆ 0.442179   ┆ 0.275104   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [23]:
w_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [24]:
w_tourney_detailed_lf = w_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [25]:
w_tourney_detailed_lf = ecm.create_team_season_profile(w_tourney_detailed_lf)
w_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2015   ┆ 3314   ┆ 74.0      ┆ 72.0        ┆ … ┆ 97.707546   ┆ 0.483363 ┆ 0.460145   ┆ 0.177206   │
│ 2018   ┆ 3370   ┆ 45.0      ┆ 88.0        ┆ … ┆ 123.552124  ┆ 0.330645 ┆ 0.564286   ┆ 0.18598    │
│ 2023   ┆ 3218   ┆ 50.0      ┆ 73.0        ┆ … ┆ 105.989111  ┆ 0.375    ┆ 0.443548   ┆ 0.269865   │
│ 2017   ┆ 3323   ┆ 85.25     ┆ 70.75       ┆ … ┆ 97.269372   ┆ 0.54474  ┆ 0.46511    ┆ 0.145924   │
│ 2018   ┆ 3177   ┆ 84.5      ┆ 79.5        ┆ … ┆ 107.737073  ┆ 0.579002 ┆ 0.444796   ┆ 0.147571   │
│ 2025   ┆ 3456   ┆ 65.0      ┆ 84.0        ┆ … ┆ 108.345464  ┆ 0.44635  ┆ 0.501075   ┆ 0.229485   │
│ 2021   ┆ 3433   ┆ 32.0      ┆ 63.0        ┆ … ┆ 99.722992   ┆ 0.245614 ┆ 0.490741   ┆ 0.210186   │
│ 2024   ┆ 3342   ┆ 44.0      ┆ 66.5        ┆ … ┆ 103.376975  ┆ 0.360417 ┆ 0.455295   ┆ 0.239947   │
│ 2023   ┆ 3266   ┆ 65.0      ┆ 67.0        ┆ … ┆ 90.632398   ┆ 0.357143 ┆ 0.4        ┆ 0.108918   │
│ 2024   ┆ 3343   ┆ 53.0      ┆ 63.0        ┆ … ┆ 95.310136   ┆ 0.392157 ┆ 0.5625     ┆ 0.269948   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [26]:
w_tourney_detailed_df: pl.DataFrame = w_tourney_detailed_lf.collect()
w_tourney_detailed_df.write_parquet("../data/proccessed/w_tourney_detailed.parquet")

In [27]:
del w_tourney_detailed_df, w_tourney_detailed_lf

In [28]:
w_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneySeeds.csv")
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [29]:
w_tourney_seed_lf = w_tourney_seed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [30]:
w_tourney_seed_lf = ecm.clean_seed(w_tourney_seed_lf)
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 3163   │
│ 2015   ┆ 2    ┆ 3246   │
│ 2015   ┆ 3    ┆ 3257   │
│ 2015   ┆ 4    ┆ 3143   │
│ 2015   ┆ 5    ┆ 3400   │
│ 2015   ┆ 6    ┆ 3378   │
│ 2015   ┆ 7    ┆ 3173   │
│ 2015   ┆ 8    ┆ 3353   │
│ 2015   ┆ 9    ┆ 3371   │
│ 2015   ┆ 10   ┆ 3235   │
└────────┴──────┴────────┘

In [31]:
w_golden_table_lf: pl.LazyFrame = ecm.merge_seed_with_regular(w_tourney_seed_lf, w_regular_season_detailed_lf)
w_golden_table_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2021   ┆ 3161   ┆ 74.894737 ┆ 67.263158     ┆ … ┆ 0.49249  ┆ 0.441452    ┆ 0.136373     ┆ null │
│ 2023   ┆ 3214   ┆ 60.172414 ┆ 66.241379     ┆ … ┆ 0.399763 ┆ 0.482674    ┆ 0.202526     ┆ null │
│ 2026   ┆ 3181   ┆ 75.818182 ┆ 59.318182     ┆ … ┆ 0.498111 ┆ 0.413763    ┆ 0.186435     ┆ null │
│ 2024   ┆ 3130   ┆ 70.969697 ┆ 69.666667     ┆ … ┆ 0.460615 ┆ 0.497172    ┆ 0.199259     ┆ null │
│ 2022   ┆ 3271   ┆ 61.6      ┆ 65.24         ┆ … ┆ 0.406619 ┆ 0.432284    ┆ 0.217517     ┆ null │
│ 2021   ┆ 3284   ┆ 46.0      ┆ 60.166667     ┆ … ┆ 0.377391 ┆ 0.424424    ┆ 0.281294     ┆ null │
│ 2015   ┆ 3201   ┆ 63.0      ┆ 59.586207     ┆ … ┆ 0.443387 ┆ 0.422503    ┆ 0.25264      ┆ null │
│ 2021   ┆ 3407   ┆ 84.28     ┆ 72.88         ┆ … ┆ 0.442737 ┆ 0.433962    ┆ 0.184292     ┆ 15   │
│ 2026   ┆ 3113   ┆ 67.083333 ┆ 58.625        ┆ … ┆ 0.470362 ┆ 0.445186    ┆ 0.221784     ┆ null │
│ 2021   ┆ 3265   ┆ 63.571429 ┆ 50.0          ┆ … ┆ 0.468031 ┆ 0.386253    ┆ 0.196606     ┆ 15   │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [32]:
del w_tourney_seed_lf, w_regular_season_detailed_lf

In [33]:
w_tourney_matchups_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_matchups_lf = ecm.prepare_tourney_matchups(w_tourney_matchups_lf)
w_tourney_matchups_lf.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ 1      │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ 1      │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ 1      │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ 1      │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ 1      │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ 1      │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ 1      │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ 1      │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ 1      │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

In [34]:
w_train_data_lf: pl.LazyFrame = ecm.finalize_training_data(w_tourney_matchups_lf, w_golden_table_lf)
w_train_data_lf.head(10).collect()

shape: (10, 17)
┌────────┬─────────┬─────────┬────────┬───┬──────────────┬──────────────┬──────────────┬───────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ … ┆ TeamEFG_Diff ┆ OpponentEFG_ ┆ TurnoverRate ┆ Seed_Diff │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---          ┆ Diff         ┆ _Diff        ┆ ---       │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆   ┆ f64          ┆ ---          ┆ ---          ┆ i8        │
│        ┆         ┆         ┆        ┆   ┆              ┆ f64          ┆ f64          ┆           │
╞════════╪═════════╪═════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪═══════════╡
│ 2015   ┆ 3116    ┆ 3321    ┆ 137    ┆ … ┆ -0.065267    ┆ -0.022153    ┆ 0.002366     ┆ 3         │
│ 2015   ┆ 3124    ┆ 3322    ┆ 137    ┆ … ┆ 0.06781      ┆ -0.053646    ┆ -0.008088    ┆ -13       │
│ 2015   ┆ 3143    ┆ 3455    ┆ 137    ┆ … ┆ 0.002632     ┆ 0.000894     ┆ 0.012675     ┆ -9        │
│ 2015   ┆ 3173    ┆ 3235    ┆ 137    ┆ … ┆ 0.010844     ┆ -0.037637    ┆ 0.030525     ┆ -3        │
│ 2015   ┆ 3177    ┆ 3278    ┆ 137    ┆ … ┆ 0.028656     ┆ 0.038958     ┆ -0.047683    ┆ 1         │
│ 2015   ┆ 3181    ┆ 3107    ┆ 137    ┆ … ┆ -0.018015    ┆ -0.041011    ┆ 0.009153     ┆ -9        │
│ 2015   ┆ 3211    ┆ 3203    ┆ 137    ┆ … ┆ 0.030676     ┆ 0.016624     ┆ 0.003185     ┆ 5         │
│ 2015   ┆ 3234    ┆ 3110    ┆ 137    ┆ … ┆ 0.03694      ┆ 0.048403     ┆ -0.012815    ┆ -11       │
│ 2015   ┆ 3246    ┆ 3398    ┆ 137    ┆ … ┆ 0.001469     ┆ -0.000361    ┆ -0.013834    ┆ -13       │
│ 2015   ┆ 3274    ┆ 3449    ┆ 137    ┆ … ┆ -0.047435    ┆ -0.002718    ┆ 0.041146     ┆ 5         │
└────────┴─────────┴─────────┴────────┴───┴──────────────┴──────────────┴──────────────┴───────────┘

In [35]:
del w_tourney_matchups_lf, w_golden_table_lf

In [36]:
w_train_data_df: pl.DataFrame = w_train_data_lf.collect()
w_train_data_df.write_parquet("../data/proccessed/w_train_data.parquet")

In [37]:
del w_train_data_df, w_train_data_lf