In [1]:
import polars as pl
import polars.selectors as cs
from src import exploration_cleaning_methods as ecm

**Men's NCCA data**

In [2]:
m_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MRegularSeasonDetailedResults.csv")
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [3]:
m_regular_season_detailed_lf = m_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 10     ┆ 1104    ┆ 68     ┆ … ┆ 18  ┆ 9    ┆ 2    ┆ 20  │
│ 2003   ┆ 10     ┆ 1272    ┆ 70     ┆ … ┆ 12  ┆ 8    ┆ 6    ┆ 16  │
│ 2003   ┆ 11     ┆ 1266    ┆ 73     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 23  │
│ 2003   ┆ 11     ┆ 1296    ┆ 56     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 23  │
│ 2003   ┆ 11     ┆ 1400    ┆ 77     ┆ … ┆ 10  ┆ 7    ┆ 1    ┆ 14  │
│ 2003   ┆ 11     ┆ 1458    ┆ 81     ┆ … ┆ 19  ┆ 4    ┆ 3    ┆ 25  │
│ 2003   ┆ 12     ┆ 1161    ┆ 80     ┆ … ┆ 30  ┆ 10   ┆ 4    ┆ 28  │
│ 2003   ┆ 12     ┆ 1186    ┆ 75     ┆ … ┆ 15  ┆ 14   ┆ 8    ┆ 18  │
│ 2003   ┆ 12     ┆ 1194    ┆ 71     ┆ … ┆ 25  ┆ 8    ┆ 2    ┆ 18  │
│ 2003   ┆ 12     ┆ 1458    ┆ 84     ┆ … ┆ 18  ┆ 1    ┆ 3    ┆ 18  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [4]:
m_regular_season_detailed_lf = ecm.create_team_season_profile(m_regular_season_detailed_lf)
m_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2023   ┆ 1334   ┆ 75.774194 ┆ 78.354839   ┆ … ┆ 107.725992  ┆ 0.525012 ┆ 0.541665   ┆ 0.153318   │
│ 2018   ┆ 1240   ┆ 70.59375  ┆ 65.625      ┆ … ┆ 97.425728   ┆ 0.506703 ┆ 0.482222   ┆ 0.190331   │
│ 2018   ┆ 1173   ┆ 72.387097 ┆ 73.451613   ┆ … ┆ 108.270391  ┆ 0.558775 ┆ 0.545175   ┆ 0.201295   │
│ 2017   ┆ 1206   ┆ 74.09375  ┆ 71.84375    ┆ … ┆ 102.107581  ┆ 0.496868 ┆ 0.48614    ┆ 0.187757   │
│ 2026   ┆ 1320   ┆ 65.681818 ┆ 61.636364   ┆ … ┆ 95.123599   ┆ 0.51389  ┆ 0.463013   ┆ 0.139491   │
│ 2016   ┆ 1191   ┆ 74.0      ┆ 65.515152   ┆ … ┆ 94.390263   ┆ 0.53475  ┆ 0.460599   ┆ 0.18139    │
│ 2026   ┆ 1223   ┆ 67.904762 ┆ 74.952381   ┆ … ┆ 114.894111  ┆ 0.515082 ┆ 0.565723   ┆ 0.174909   │
│ 2026   ┆ 1236   ┆ 74.571429 ┆ 79.285714   ┆ … ┆ 112.674861  ┆ 0.527078 ┆ 0.566426   ┆ 0.129594   │
│ 2021   ┆ 1239   ┆ 65.681818 ┆ 70.090909   ┆ … ┆ 100.936391  ┆ 0.488832 ┆ 0.51453    ┆ 0.194104   │
│ 2019   ┆ 1132   ┆ 77.96875  ┆ 74.59375    ┆ … ┆ 102.056313  ┆ 0.51108  ┆ 0.509321   ┆ 0.165671   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [5]:
m_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [6]:
m_tourney_detailed_lf = m_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
m_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2003   ┆ 134    ┆ 1421    ┆ 92     ┆ … ┆ 15  ┆ 5    ┆ 0    ┆ 22  │
│ 2003   ┆ 136    ┆ 1112    ┆ 80     ┆ … ┆ 17  ┆ 10   ┆ 3    ┆ 15  │
│ 2003   ┆ 136    ┆ 1113    ┆ 84     ┆ … ┆ 12  ┆ 2    ┆ 5    ┆ 18  │
│ 2003   ┆ 136    ┆ 1141    ┆ 79     ┆ … ┆ 21  ┆ 6    ┆ 6    ┆ 21  │
│ 2003   ┆ 136    ┆ 1143    ┆ 76     ┆ … ┆ 14  ┆ 5    ┆ 8    ┆ 19  │
│ 2003   ┆ 136    ┆ 1163    ┆ 58     ┆ … ┆ 11  ┆ 8    ┆ 4    ┆ 22  │
│ 2003   ┆ 136    ┆ 1181    ┆ 67     ┆ … ┆ 19  ┆ 5    ┆ 4    ┆ 19  │
│ 2003   ┆ 136    ┆ 1211    ┆ 74     ┆ … ┆ 10  ┆ 7    ┆ 6    ┆ 24  │
│ 2003   ┆ 136    ┆ 1228    ┆ 65     ┆ … ┆ 14  ┆ 6    ┆ 5    ┆ 16  │
│ 2003   ┆ 136    ┆ 1242    ┆ 64     ┆ … ┆ 13  ┆ 6    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [7]:
m_tourney_detailed_lf = ecm.create_team_season_profile(m_tourney_detailed_lf)
m_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2025   ┆ 1252   ┆ 55.0      ┆ 82.0        ┆ … ┆ 119.186047  ┆ 0.45098  ┆ 0.641667   ┆ 0.247453   │
│ 2015   ┆ 1352   ┆ 68.5      ┆ 81.0        ┆ … ┆ 122.563559  ┆ 0.446481 ┆ 0.644765   ┆ 0.097477   │
│ 2015   ┆ 1437   ┆ 80.5      ┆ 61.5        ┆ … ┆ 97.564202   ┆ 0.556658 ┆ 0.449657   ┆ 0.100884   │
│ 2023   ┆ 1234   ┆ 75.0      ┆ 83.0        ┆ … ┆ 113.002042  ┆ 0.463235 ┆ 0.52381    ┆ 0.110995   │
│ 2024   ┆ 1255   ┆ 46.0      ┆ 86.0        ┆ … ┆ 139.95118   ┆ 0.378049 ┆ 0.688679   ┆ 0.28754    │
│ 2019   ┆ 1295   ┆ 70.0      ┆ 79.5        ┆ … ┆ 120.476597  ┆ 0.499171 ┆ 0.534615   ┆ 0.139579   │
│ 2025   ┆ 1276   ┆ 74.666667 ┆ 74.0        ┆ … ┆ 101.646049  ┆ 0.458409 ┆ 0.441277   ┆ 0.176435   │
│ 2017   ┆ 1245   ┆ 80.0      ┆ 97.0        ┆ … ┆ 138.720057  ┆ 0.5      ┆ 0.686441   ┆ 0.114778   │
│ 2024   ┆ 1324   ┆ 76.5      ┆ 77.5        ┆ … ┆ 110.727028  ┆ 0.493814 ┆ 0.511719   ┆ 0.086421   │
│ 2015   ┆ 1207   ┆ 74.0      ┆ 74.5        ┆ … ┆ 117.195913  ┆ 0.576799 ┆ 0.580387   ┆ 0.181387   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [8]:
m_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneySeeds.csv")
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [9]:
m_tourney_seed_lf = m_tourney_seed_lf.with_columns(cs.numeric().exclude("Seed").cast(pl.Int16))
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
│ 1985   ┆ W06  ┆ 1208   │
│ 1985   ┆ W07  ┆ 1393   │
│ 1985   ┆ W08  ┆ 1396   │
│ 1985   ┆ W09  ┆ 1439   │
│ 1985   ┆ W10  ┆ 1177   │
└────────┴──────┴────────┘

In [10]:
m_tourney_seed_lf = ecm.clean_seed(m_tourney_seed_lf)
m_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 1437   │
│ 2015   ┆ 2    ┆ 1438   │
│ 2015   ┆ 3    ┆ 1328   │
│ 2015   ┆ 4    ┆ 1257   │
│ 2015   ┆ 5    ┆ 1320   │
│ 2015   ┆ 6    ┆ 1344   │
│ 2015   ┆ 7    ┆ 1277   │
│ 2015   ┆ 8    ┆ 1301   │
│ 2015   ┆ 9    ┆ 1261   │
│ 2015   ┆ 10   ┆ 1208   │
└────────┴──────┴────────┘

In [11]:
m_golden_tabel_lf: pl.LazyFrame = ecm.merge_seed_with_regular(m_tourney_seed_lf, m_regular_season_detailed_lf)
m_golden_tabel_lf.head(10).collect()

shape: (10, 14)
┌────────┬────────┬───────────┬───────────────┬───┬──────────┬─────────────┬──────────────┬──────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentScore ┆ … ┆ TeamEFG  ┆ OpponentEFG ┆ TurnoverRate ┆ Seed │
│ ---    ┆ ---    ┆ ---       ┆ ---           ┆   ┆ ---      ┆ ---         ┆ ---          ┆ ---  │
│ i16    ┆ i16    ┆ f64       ┆ f64           ┆   ┆ f64      ┆ f64         ┆ f64          ┆ i8   │
╞════════╪════════╪═══════════╪═══════════════╪═══╪══════════╪═════════════╪══════════════╪══════╡
│ 2024   ┆ 1428   ┆ 78.060606 ┆ 72.636364     ┆ … ┆ 0.537765 ┆ 0.486563    ┆ 0.154631     ┆ null │
│ 2023   ┆ 1464   ┆ 80.903226 ┆ 73.0          ┆ … ┆ 0.555342 ┆ 0.52262     ┆ 0.148447     ┆ null │
│ 2023   ┆ 1247   ┆ 69.823529 ┆ 72.588235     ┆ … ┆ 0.489434 ┆ 0.514035    ┆ 0.170019     ┆ null │
│ 2021   ┆ 1239   ┆ 65.681818 ┆ 70.090909     ┆ … ┆ 0.488832 ┆ 0.51453     ┆ 0.194104     ┆ null │
│ 2024   ┆ 1402   ┆ 67.515152 ┆ 70.484848     ┆ … ┆ 0.47308  ┆ 0.498239    ┆ 0.181887     ┆ null │
│ 2017   ┆ 1397   ┆ 73.806452 ┆ 72.709677     ┆ … ┆ 0.467997 ┆ 0.488781    ┆ 0.173189     ┆ null │
│ 2022   ┆ 1360   ┆ 63.931034 ┆ 68.724138     ┆ … ┆ 0.468601 ┆ 0.49293     ┆ 0.173242     ┆ null │
│ 2019   ┆ 1149   ┆ 73.0      ┆ 70.964286     ┆ … ┆ 0.503984 ┆ 0.513641    ┆ 0.177765     ┆ null │
│ 2015   ┆ 1163   ┆ 64.176471 ┆ 59.794118     ┆ … ┆ 0.503074 ┆ 0.44833     ┆ 0.183488     ┆ null │
│ 2015   ┆ 1185   ┆ 68.233333 ┆ 65.933333     ┆ … ┆ 0.473087 ┆ 0.466625    ┆ 0.178018     ┆ null │
└────────┴────────┴───────────┴───────────────┴───┴──────────┴─────────────┴──────────────┴──────┘

In [12]:
del m_regular_season_detailed_lf, m_tourney_seed_lf

In [13]:
m_tourney_matchups: pl.LazyFrame = pl.scan_csv("../data/raw/MNCAATourneyDetailedResults.csv")
m_tourney_matchups = ecm.prepare_tourney_matchups(m_tourney_matchups)
m_tourney_matchups.head(10).collect()

shape: (10, 5)
┌────────┬─────────┬─────────┬────────┬────────┐
│ Season ┆ ATeamID ┆ BTeamID ┆ DayNum ┆ Target │
│ ---    ┆ ---     ┆ ---     ┆ ---    ┆ ---    │
│ i16    ┆ i16     ┆ i16     ┆ i16    ┆ i8     │
╞════════╪═════════╪═════════╪════════╪════════╡
│ 2015   ┆ 1214    ┆ 1264    ┆ 134    ┆ 1      │
│ 2015   ┆ 1279    ┆ 1140    ┆ 134    ┆ 1      │
│ 2015   ┆ 1173    ┆ 1129    ┆ 135    ┆ 1      │
│ 2015   ┆ 1352    ┆ 1316    ┆ 135    ┆ 1      │
│ 2015   ┆ 1112    ┆ 1411    ┆ 136    ┆ 1      │
│ 2015   ┆ 1116    ┆ 1459    ┆ 136    ┆ 1      │
│ 2015   ┆ 1139    ┆ 1400    ┆ 136    ┆ 1      │
│ 2015   ┆ 1153    ┆ 1345    ┆ 136    ┆ 1      │
│ 2015   ┆ 1207    ┆ 1186    ┆ 136    ┆ 1      │
│ 2015   ┆ 1209    ┆ 1124    ┆ 136    ┆ 1      │
└────────┴─────────┴─────────┴────────┴────────┘

**Women's NCCA data**

In [14]:
w_regular_season_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WRegularSeasonDetailedResults.csv")
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [15]:
w_regular_season_detailed_lf = w_regular_season_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 11     ┆ 3103    ┆ 63     ┆ … ┆ 23  ┆ 7    ┆ 6    ┆ 19  │
│ 2010   ┆ 11     ┆ 3104    ┆ 73     ┆ … ┆ 20  ┆ 4    ┆ 2    ┆ 27  │
│ 2010   ┆ 11     ┆ 3110    ┆ 71     ┆ … ┆ 15  ┆ 6    ┆ 0    ┆ 15  │
│ 2010   ┆ 11     ┆ 3111    ┆ 63     ┆ … ┆ 11  ┆ 14   ┆ 5    ┆ 14  │
│ 2010   ┆ 11     ┆ 3119    ┆ 74     ┆ … ┆ 14  ┆ 4    ┆ 2    ┆ 14  │
│ 2010   ┆ 11     ┆ 3120    ┆ 70     ┆ … ┆ 29  ┆ 9    ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3125    ┆ 85     ┆ … ┆ 15  ┆ 10   ┆ 0    ┆ 22  │
│ 2010   ┆ 11     ┆ 3132    ┆ 76     ┆ … ┆ 28  ┆ 8    ┆ 1    ┆ 17  │
│ 2010   ┆ 11     ┆ 3138    ┆ 87     ┆ … ┆ 21  ┆ 11   ┆ 1    ┆ 28  │
│ 2010   ┆ 11     ┆ 3140    ┆ 73     ┆ … ┆ 22  ┆ 2    ┆ 1    ┆ 15  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [16]:
w_regular_season_detailed_lf = ecm.create_team_season_profile(w_regular_season_detailed_lf)
w_regular_season_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2018   ┆ 3282   ┆ 64.111111 ┆ 67.592593   ┆ … ┆ 97.968388   ┆ 0.451836 ┆ 0.499582   ┆ 0.212441   │
│ 2019   ┆ 3316   ┆ 63.925926 ┆ 67.037037   ┆ … ┆ 92.694806   ┆ 0.44525  ┆ 0.459442   ┆ 0.214632   │
│ 2024   ┆ 3114   ┆ 55.633333 ┆ 60.666667   ┆ … ┆ 89.781381   ┆ 0.4275   ┆ 0.470202   ┆ 0.202528   │
│ 2015   ┆ 3348   ┆ 57.933333 ┆ 59.3        ┆ … ┆ 86.297336   ┆ 0.432199 ┆ 0.420066   ┆ 0.245261   │
│ 2018   ┆ 3326   ┆ 85.121212 ┆ 71.151515   ┆ … ┆ 93.543043   ┆ 0.516453 ┆ 0.465361   ┆ 0.149933   │
│ 2022   ┆ 3173   ┆ 65.5      ┆ 54.733333   ┆ … ┆ 78.753607   ┆ 0.449679 ┆ 0.396082   ┆ 0.17375    │
│ 2025   ┆ 3114   ┆ 61.206897 ┆ 66.758621   ┆ … ┆ 94.612201   ┆ 0.425062 ┆ 0.489701   ┆ 0.198772   │
│ 2025   ┆ 3459   ┆ 63.08     ┆ 64.08       ┆ … ┆ 91.009885   ┆ 0.429777 ┆ 0.440902   ┆ 0.184887   │
│ 2024   ┆ 3460   ┆ 69.225806 ┆ 71.83871    ┆ … ┆ 96.815359   ┆ 0.47786  ┆ 0.488562   ┆ 0.179858   │
│ 2015   ┆ 3261   ┆ 63.233333 ┆ 60.066667   ┆ … ┆ 86.504511   ┆ 0.433986 ┆ 0.449925   ┆ 0.243789   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [17]:
w_tourney_detailed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneyDetailedResults.csv")
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆   ┆ i64 ┆ i64  ┆ i64  ┆ i64 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [18]:
w_tourney_detailed_lf = w_tourney_detailed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_detailed_lf.head(10).collect()

shape: (10, 34)
┌────────┬────────┬─────────┬────────┬───┬─────┬──────┬──────┬─────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ … ┆ LTO ┆ LStl ┆ LBlk ┆ LPF │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆   ┆ --- ┆ ---  ┆ ---  ┆ --- │
│ i16    ┆ i16    ┆ i16     ┆ i16    ┆   ┆ i16 ┆ i16  ┆ i16  ┆ i16 │
╞════════╪════════╪═════════╪════════╪═══╪═════╪══════╪══════╪═════╡
│ 2010   ┆ 138    ┆ 3124    ┆ 69     ┆ … ┆ 18  ┆ 4    ┆ 1    ┆ 18  │
│ 2010   ┆ 138    ┆ 3173    ┆ 67     ┆ … ┆ 8   ┆ 8    ┆ 6    ┆ 22  │
│ 2010   ┆ 138    ┆ 3181    ┆ 72     ┆ … ┆ 16  ┆ 6    ┆ 4    ┆ 20  │
│ 2010   ┆ 138    ┆ 3199    ┆ 75     ┆ … ┆ 16  ┆ 5    ┆ 4    ┆ 24  │
│ 2010   ┆ 138    ┆ 3207    ┆ 62     ┆ … ┆ 10  ┆ 3    ┆ 4    ┆ 12  │
│ 2010   ┆ 138    ┆ 3208    ┆ 64     ┆ … ┆ 12  ┆ 11   ┆ 3    ┆ 20  │
│ 2010   ┆ 138    ┆ 3211    ┆ 82     ┆ … ┆ 18  ┆ 12   ┆ 5    ┆ 16  │
│ 2010   ┆ 138    ┆ 3234    ┆ 70     ┆ … ┆ 13  ┆ 10   ┆ 2    ┆ 21  │
│ 2010   ┆ 138    ┆ 3246    ┆ 83     ┆ … ┆ 22  ┆ 8    ┆ 1    ┆ 25  │
│ 2010   ┆ 138    ┆ 3261    ┆ 60     ┆ … ┆ 17  ┆ 7    ┆ 5    ┆ 20  │
└────────┴────────┴─────────┴────────┴───┴─────┴──────┴──────┴─────┘

In [19]:
w_tourney_detailed_lf = ecm.create_team_season_profile(w_tourney_detailed_lf)
w_tourney_detailed_lf.head(10).collect()

shape: (10, 13)
┌────────┬────────┬───────────┬─────────────┬───┬─────────────┬──────────┬────────────┬────────────┐
│ Season ┆ TeamID ┆ TeamScore ┆ OpponentSco ┆ … ┆ DefEfficien ┆ TeamEFG  ┆ OpponentEF ┆ TurnoverRa │
│ ---    ┆ ---    ┆ ---       ┆ re          ┆   ┆ cy          ┆ ---      ┆ G          ┆ te         │
│ i16    ┆ i16    ┆ f64       ┆ ---         ┆   ┆ ---         ┆ f64      ┆ ---        ┆ ---        │
│        ┆        ┆           ┆ f64         ┆   ┆ f64         ┆          ┆ f64        ┆ f64        │
╞════════╪════════╪═══════════╪═════════════╪═══╪═════════════╪══════════╪════════════╪════════════╡
│ 2016   ┆ 3299   ┆ 61.0      ┆ 95.0        ┆ … ┆ 116.172424  ┆ 0.380597 ┆ 0.637931   ┆ 0.234785   │
│ 2015   ┆ 3378   ┆ 62.5      ┆ 62.0        ┆ … ┆ 91.149263   ┆ 0.409696 ┆ 0.387042   ┆ 0.215949   │
│ 2021   ┆ 3277   ┆ 75.0      ┆ 79.0        ┆ … ┆ 110.799439  ┆ 0.484127 ┆ 0.517544   ┆ 0.159478   │
│ 2024   ┆ 3163   ┆ 72.0      ┆ 63.4        ┆ … ┆ 84.025024   ┆ 0.527862 ┆ 0.416453   ┆ 0.188018   │
│ 2017   ┆ 3146   ┆ 50.0      ┆ 78.0        ┆ … ┆ 112.149533  ┆ 0.34127  ┆ 0.55       ┆ 0.149813   │
│ 2018   ┆ 3453   ┆ 77.0      ┆ 89.0        ┆ … ┆ 122.294744  ┆ 0.457746 ┆ 0.542373   ┆ 0.165289   │
│ 2022   ┆ 3193   ┆ 52.0      ┆ 70.0        ┆ … ┆ 100.937275  ┆ 0.392857 ┆ 0.465517   ┆ 0.286021   │
│ 2023   ┆ 3284   ┆ 69.0      ┆ 79.0        ┆ … ┆ 117.866468  ┆ 0.465517 ┆ 0.574074   ┆ 0.146897   │
│ 2025   ┆ 3435   ┆ 73.0      ┆ 77.0        ┆ … ┆ 97.684745   ┆ 0.38806  ┆ 0.534483   ┆ 0.152333   │
│ 2018   ┆ 3328   ┆ 79.0      ┆ 90.0        ┆ … ┆ 115.569823  ┆ 0.442623 ┆ 0.62069    ┆ 0.150612   │
└────────┴────────┴───────────┴─────────────┴───┴─────────────┴──────────┴────────────┴────────────┘

In [20]:
w_tourney_seed_lf: pl.LazyFrame = pl.scan_csv("../data/raw/WNCAATourneySeeds.csv")
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [21]:
w_tourney_seed_lf = w_tourney_seed_lf.with_columns(cs.numeric().exclude("WLoc").cast(pl.Int16))
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ str  ┆ i16    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
│ 1998   ┆ W06  ┆ 3438   │
│ 1998   ┆ W07  ┆ 3208   │
│ 1998   ┆ W08  ┆ 3307   │
│ 1998   ┆ W09  ┆ 3304   │
│ 1998   ┆ W10  ┆ 3203   │
└────────┴──────┴────────┘

In [22]:
w_tourney_seed_lf = ecm.clean_seed(w_tourney_seed_lf)
w_tourney_seed_lf.head(10).collect()

shape: (10, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i16    ┆ i8   ┆ i16    │
╞════════╪══════╪════════╡
│ 2015   ┆ 1    ┆ 3163   │
│ 2015   ┆ 2    ┆ 3246   │
│ 2015   ┆ 3    ┆ 3257   │
│ 2015   ┆ 4    ┆ 3143   │
│ 2015   ┆ 5    ┆ 3400   │
│ 2015   ┆ 6    ┆ 3378   │
│ 2015   ┆ 7    ┆ 3173   │
│ 2015   ┆ 8    ┆ 3353   │
│ 2015   ┆ 9    ┆ 3371   │
│ 2015   ┆ 10   ┆ 3235   │
└────────┴──────┴────────┘